<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="AX_2_2" Comment="AX_OR and AX_SPLIT for a 2-to-2 Connection">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2026-05-29">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<Plugs>
			<AdapterDeclaration Name="OUT1" Type="adapter::types::unidirectional::AX"/>
			<AdapterDeclaration Name="OUT2" Type="adapter::types::unidirectional::AX"/>
		</Plugs>
		<Sockets>
			<AdapterDeclaration Name="IN1" Type="adapter::types::unidirectional::AX"/>
			<AdapterDeclaration Name="IN2" Type="adapter::types::unidirectional::AX"/>
		</Sockets>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="AX_SPLIT_2" Type="adapter::events::unidirectional::AX_SPLIT_2" x="1300" y="-1000">
		</FB>
		<FB Name="AX_OR_2" Type="adapter::booleanOperators::AX_OR_2" x="300" y="-1000">
		</FB>
		<AdapterConnections>
			<Connection Source="AX_OR_2.OUT" Destination="AX_SPLIT_2.IN"/>
			<Connection Source="AX_SPLIT_2.OUT1" Destination="OUT1" dx1="2486.67"/>
			<Connection Source="AX_SPLIT_2.OUT2" Destination="OUT2" dx1="2486.67"/>
			<Connection Source="IN1" Destination="AX_OR_2.IN1" dx1="1386.67"/>
			<Connection Source="IN2" Destination="AX_OR_2.IN2" dx1="1386.67"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
