<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="AX_GT_0_UINT" Comment="Prüft ob UINT-Adapter Wert &gt; 0 ist (AX-Adapter Ausgang)">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2026-04-20">
	</VersionInfo>
	<CompilerInfo packageName="MyLib::sys">
	</CompilerInfo>
	<SubAppInterfaceList>
		<Plugs>
			<AdapterDeclaration Name="AX_OUT" Type="adapter::types::unidirectional::AX"/>
		</Plugs>
		<Sockets>
			<AdapterDeclaration Name="IN" Type="adapter::types::unidirectional::AUI"/>
		</Sockets>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="AUI_UI_TO_UINT" Type="adapter::conversion::unidirectional::AUI_UI_TO_UINT" x="713.33" y="33.33">
		</FB>
		<FB Name="AX_BOOL_TO_X" Type="adapter::conversion::unidirectional::AX_BOOL_TO_X" x="3046.67" y="33.33">
		</FB>
		<FB Name="F_GT" Type="iec61131::comparison::F_GT" x="2260" y="33.33">
			<Parameter Name="IN2" Value="UINT#0"/>
		</FB>
		<EventConnections>
			<Connection Source="AUI_UI_TO_UINT.CNF" Destination="F_GT.REQ"/>
			<Connection Source="F_GT.CNF" Destination="AX_BOOL_TO_X.REQ"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="AUI_UI_TO_UINT.IN" Destination="F_GT.IN1"/>
			<Connection Source="F_GT.OUT" Destination="AX_BOOL_TO_X.OUT"/>
		</DataConnections>
		<AdapterConnections>
			<Connection Source="IN" Destination="AUI_UI_TO_UINT.AUI_IN" dx1="1546.67"/>
			<Connection Source="AX_BOOL_TO_X.AX_OUT" Destination="AX_OUT" dx1="513.33"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
