<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="AX_LinksRechts_T_FF" Comment="Links/Rechts Umschaltung mittels Toggle-Flip-Flop (AX-Adapter)">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-01-13" Remarks="initial API and implementation and/or initial documentation">
	</VersionInfo>
	<CompilerInfo packageName="MyLib::sys">
	</CompilerInfo>
	<SubAppInterfaceList>
		<Plugs>
			<AdapterDeclaration Name="Links" Type="adapter::types::unidirectional::AX"/>
			<AdapterDeclaration Name="Rechts" Type="adapter::types::unidirectional::AX"/>
		</Plugs>
		<Sockets>
			<AdapterDeclaration Name="IN" Type="adapter::types::unidirectional::AX"/>
		</Sockets>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="AX_T_FF_INIT" Type="adapter::events::unidirectional::AX_T_FF_INIT" x="100" y="-500">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Q_INIT" Value="FALSE"/>
		</FB>
		<FB Name="AX_R_TRIG" Type="adapter::events::unidirectional::AX_R_TRIG" x="-1200" y="-400">
		</FB>
		<FB Name="AX_NOT" Type="adapter::booleanOperators::AX_NOT" x="2900" y="-800">
		</FB>
		<FB Name="AX_SPLIT_2" Type="adapter::events::unidirectional::AX_SPLIT_2" x="1500" y="-100">
		</FB>
		<Comment Comment="der AX_T_FF_INIT schaltet den Ausgang Aktiv auf FALSE, somit ist LINKS dann TRUE. " x="0" y="500" width="1600" height="400"/>
		<EventConnections>
			<Connection Source="AX_R_TRIG.EO" Destination="AX_T_FF_INIT.CLK" dx1="293.33"/>
		</EventConnections>
		<AdapterConnections>
			<Connection Source="IN" Destination="AX_R_TRIG.QI" dx1="664.71"/>
			<Connection Source="AX_NOT.OUT" Destination="Links" dx1="711.76"/>
			<Connection Source="AX_T_FF_INIT.Q" Destination="AX_SPLIT_2.IN" dx1="273.33"/>
			<Connection Source="AX_SPLIT_2.OUT1" Destination="AX_NOT.IN" dx1="266.67"/>
			<Connection Source="AX_SPLIT_2.OUT2" Destination="Rechts" dx1="2340"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
