<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="GreenWhiteBackground1SC" Comment="Hintergrundfarbe (TRUE -&gt; Grün, FALSE -&gt; Weiß) für 1 Objekt (Kompakt)">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2024-01-01">
	</VersionInfo>
	<CompilerInfo packageName="MyLib::sys">
		<Import declaration="isobus::UT::Q::const::IDs::ID_NULL"/>
		<Import declaration="isobus::UT::Q::types::s1ObjectID"/>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="EO" Type="Event">
			</SubAppEvent>
		</SubAppEventInputs>
		<InputVars>
			<VarDeclaration Name="DI1" Type="BOOL" Comment="Selector"/>
			<VarDeclaration Name="u16ObjIds" Type="isobus::UT::Q::types::s1ObjectID" Comment="Object IDs" InitialValue="(u16ObjId := ID_NULL)"/>
		</InputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<SubApp Name="GreenWhiteBackground" Type="MyLib::sys::GreenWhiteBackground1S" x="1700" y="-800">
		</SubApp>
		<EventConnections>
			<Connection Source="EO" Destination="GreenWhiteBackground.REQ" dx1="666.67"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="u16ObjIds" Destination="GreenWhiteBackground.u16ObjIds" dx1="400"/>
			<Connection Source="DI1" Destination="GreenWhiteBackground.DI1" dx1="606.67"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
