<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="GreenWhiteBackground4C" Comment="Hintergrundfarbe (TRUE -&gt; Grün, FALSE -&gt; Weiß) für 4 Objekte (Kompakt)">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-02-11">
	</VersionInfo>
	<CompilerInfo packageName="MyLib::sys">
		<Import declaration="isobus::UT::Q::const::IDs::ID_NULL"/>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="EO" Type="Event">
			</SubAppEvent>
		</SubAppEventInputs>
		<InputVars>
			<VarDeclaration Name="DI1" Type="BOOL" Comment="Selector"/>
			<VarDeclaration Name="u16ObjId" Type="UINT" Comment="Object ID Softkey" InitialValue="ID_NULL"/>
			<VarDeclaration Name="u16ObjIdA" Type="UINT" Comment="Object ID AUX" InitialValue="ID_NULL"/>
			<VarDeclaration Name="u16ObjIdB" Type="UINT" Comment="Object ID Button" InitialValue="ID_NULL"/>
		</InputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<SubApp Name="GreenWhiteBackground" Type="MyLib::sys::GreenWhiteBackground4" x="1700" y="-800">
		</SubApp>
		<EventConnections>
			<Connection Source="EO" Destination="GreenWhiteBackground.REQ" dx1="666.67"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="u16ObjId" Destination="GreenWhiteBackground.u16ObjId" dx1="600"/>
			<Connection Source="u16ObjIdA" Destination="GreenWhiteBackground.u16ObjIdA" dx1="566.67"/>
			<Connection Source="u16ObjIdB" Destination="GreenWhiteBackground.u16ObjIdB" dx1="533.33"/>
			<Connection Source="DI1" Destination="GreenWhiteBackground.DI1" dx1="633.33"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
