<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="GreenWhiteBackground2S" Comment="Hintergrundfarbe (TRUE -> Grün, FALSE -> Weiß) für 2 Objekte">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2024-01-01">
	</VersionInfo>
	<CompilerInfo packageName="MyLib::sys">
		<Import declaration="isobus::UT::Q::const::IDs::ID_NULL"/>
		<Import declaration="isobus::UT::Q::const::colours"/>
		<Import declaration="isobus::UT::Q::types::s2ObjectIDs"/>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="REQ" Type="Event" Comment="Normal Execution Request">
			</SubAppEvent>
		</SubAppEventInputs>
		<SubAppEventOutputs>
			<SubAppEvent Name="CNF_2" Type="Event">
			</SubAppEvent>
			<SubAppEvent Name="CNF_3" Type="Event">
			</SubAppEvent>
		</SubAppEventOutputs>
		<InputVars>
			<VarDeclaration Name="DI1" Type="BOOL" Comment="Selector"/>
			<VarDeclaration Name="u16ObjIds" Type="isobus::UT::Q::types::s2ObjectIDs" Comment="Object IDs" InitialValue="(u16ObjId := ID_NULL, u16ObjIdA := ID_NULL)"/>
		</InputVars>
		<OutputVars>
			<VarDeclaration Name="STATUS_2" Type="STRING" Comment="Service Status"/>
			<VarDeclaration Name="u8OldColour_2" Type="USINT" Comment="Old value of ID"/>
			<VarDeclaration Name="result_2" Type="INT" Comment="retval see description"/>
			<VarDeclaration Name="STATUS_3" Type="STRING" Comment="Service Status"/>
			<VarDeclaration Name="u8OldColour_3" Type="USINT" Comment="Old value of ID"/>
			<VarDeclaration Name="result_3" Type="INT" Comment="retval see description"/>
		</OutputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="Q_BackgroundColour_2" Type="isobus::UT::Q::Q_BackgroundColour" x="300" y="300">
		</FB>
		<FB Name="Q_BackgroundColour_3" Type="isobus::UT::Q::Q_BackgroundColourAux" x="300" y="1100">
		</FB>
		<FB Name="F_SEL_I" Type="iec61131::selection::F_SEL" x="-3400" y="900">
			<Parameter Name="IN0" Value="colours::COLOR_WHITE"/>
			<Parameter Name="IN1" Value="colours::COLOR_GREEN"/>
		</FB>
		<FB Name="F_MOVE" Type="iec61131::selection::F_MOVE" x="-5000" y="900">
			<Attribute Name="DataType" Value="isobus::UT::Q::types::s2ObjectIDs"/>
			<Parameter Name="OUT.u16ObjId" Value="">
				<Attribute Name="Visible" Value="true"/>
			</Parameter>
			<Parameter Name="OUT.u16ObjIdA" Value="">
				<Attribute Name="Visible" Value="true"/>
			</Parameter>
		</FB>
		<EventConnections>
			<Connection Source="Q_BackgroundColour_3.CNF" Destination="CNF_3" dx1="993.33"/>
			<Connection Source="Q_BackgroundColour_2.CNF" Destination="CNF_2" dx1="913.33"/>
			<Connection Source="REQ" Destination="F_MOVE.REQ" dx1="80"/>
			<Connection Source="F_MOVE.CNF" Destination="F_SEL_I.REQ" dx1="200"/>
			<Connection Source="F_SEL_I.CNF" Destination="Q_BackgroundColour_2.REQ" dx1="1193.33"/>
			<Connection Source="F_SEL_I.CNF" Destination="Q_BackgroundColour_3.REQ" dx1="1193.33"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="u16ObjIds" Destination="F_MOVE.IN" dx1="80"/>
			<Connection Source="F_MOVE.OUT.u16ObjIdA" Destination="Q_BackgroundColour_2.u16ObjId" dx1="160"/>
			<Connection Source="F_MOVE.OUT.u16ObjIdA" Destination="Q_BackgroundColour_3.u16ObjId" dx1="133.33"/>
			<Connection Source="Q_BackgroundColour_3.s16result" Destination="result_3" dx1="240"/>
			<Connection Source="Q_BackgroundColour_3.u8OldColour" Destination="u8OldColour_3" dx1="340"/>
			<Connection Source="Q_BackgroundColour_3.STATUS" Destination="STATUS_3" dx1="460"/>
			<Connection Source="Q_BackgroundColour_2.s16result" Destination="result_2" dx1="700"/>
			<Connection Source="Q_BackgroundColour_2.u8OldColour" Destination="u8OldColour_2" dx1="800"/>
			<Connection Source="Q_BackgroundColour_2.STATUS" Destination="STATUS_2" dx1="920"/>
			<Connection Source="DI1" Destination="F_SEL_I.G" dx1="1726.67"/>
			<Connection Source="F_SEL_I.OUT" Destination="Q_BackgroundColour_2.u8Colour" dx1="1593.33"/>
			<Connection Source="F_SEL_I.OUT" Destination="Q_BackgroundColour_3.u8Colour" dx1="753.33"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
