<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="GreenRedBackground1_aux_AXSC" Comment="Hintergrundfarbe (TRUE -&gt; Grün, FALSE -&gt; Rot) für 1 Objekt (AX-Adapter) (Kompakt)">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="Franz Höpfinger" Date="2022-11-10">
	</VersionInfo>
	<CompilerInfo packageName="MyLib::sys">
		<Import declaration="isobus::UT::Q::const::IDs::ID_NULL"/>
		<Import declaration="isobus::UT::Q::types::s1ObjectID"/>
	</CompilerInfo>
	<SubAppInterfaceList>
		<InputVars>
			<VarDeclaration Name="u16ObjIds" Type="isobus::UT::Q::types::s1ObjectID" Comment="Object ID" InitialValue="(u16ObjId := ID_NULL)"/>
		</InputVars>
		<Sockets>
			<AdapterDeclaration Name="DI1" Type="adapter::types::unidirectional::AX" Comment="Selector"/>
		</Sockets>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<SubApp Name="GreenRedBackground" Type="MyLib::sys::GreenRedBackground1_aux_AXS" x="1700" y="-800">
		</SubApp>
		<DataConnections>
			<Connection Source="u16ObjIds" Destination="GreenRedBackground.u16ObjIds" dx1="866.67"/>
		</DataConnections>
		<AdapterConnections>
			<Connection Source="DI1" Destination="GreenRedBackground.DI1" dx1="660"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
