<?xml version='1.0' encoding='UTF-8'?>
<SubAppType Name="GreenWhiteBackground2_AXSC" Comment="Hintergrundfarbe (TRUE -&gt; Grün, FALSE -&gt; Weiß) für 2 Objekte (AX-Adapter) (Kompakt)">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="Franz Höpfinger" Date="2022-11-10">
	</VersionInfo>
	<CompilerInfo packageName="MyLib::sys">
		<Import declaration="isobus::UT::Q::const::IDs::ID_NULL" />
		<Import declaration="isobus::UT::Q::types::s2ObjectIDs" />
	</CompilerInfo>
	<SubAppInterfaceList>
		<InputVars>
			<VarDeclaration Name="u16ObjIds" Type="isobus::UT::Q::types::s2ObjectIDs" Comment="Object IDs" InitialValue="(u16ObjId := ID_NULL, u16ObjIdA := ID_NULL)" />
		</InputVars>
		<Sockets>
			<AdapterDeclaration Name="DI1" Type="adapter::types::unidirectional::AX" Comment="Selector" />
		</Sockets>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<SubApp Name="GreenWhiteBackground" Type="MyLib::sys::GreenWhiteBackground2_AXS" x="1000" y="500">
		</SubApp>
		<DataConnections>
			<Connection Source="u16ObjIds" Destination="GreenWhiteBackground.u16ObjIds" dx1="100" />
		</DataConnections>
		<AdapterConnections>
			<Connection Source="DI1" Destination="GreenWhiteBackground.DI1" dx1="100" />
		</AdapterConnections>
		<EventConnections />
	</SubAppNetwork>
</SubAppType>