<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="RedGreenBackground4C" Comment="Hintergrundfarbe (TRUE -&gt; Rot, FALSE -&gt; Grün) für 4 Objekte (Kompakt)">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2022-11-10">
	</VersionInfo>
	<CompilerInfo packageName="MyLib::sys">
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="REQ" Type="Event" Comment="Normal Execution Request">
				<Attribute Name="YPOSITION" Type="USINT" Value="175"/>
			</SubAppEvent>
		</SubAppEventInputs>
		<InputVars>
			<VarDeclaration Name="DI1" Type="BOOL" Comment="Selector">
				<Attribute Name="YPOSITION" Type="SINT" Value="18"/>
			</VarDeclaration>
			<VarDeclaration Name="u16ObjId" Type="UINT" Comment="Object ID Softkey">
				<Attribute Name="YPOSITION" Type="SINT" Value="45"/>
			</VarDeclaration>
			<VarDeclaration Name="u16ObjIdA" Type="UINT" Comment="Object ID AUX">
				<Attribute Name="YPOSITION" Type="SINT" Value="105"/>
			</VarDeclaration>
			<VarDeclaration Name="u16ObjIdB" Type="UINT"/>
		</InputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<SubApp Name="RedGreenBackground4" Type="MyLib::sys::RedGreenBackground4" x="2600" y="1500">
		</SubApp>
		<EventConnections>
			<Connection Source="REQ" Destination="RedGreenBackground4.REQ" dx1="1733.33"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="DI1" Destination="RedGreenBackground4.DI1" dx1="1733.33"/>
			<Connection Source="u16ObjId" Destination="RedGreenBackground4.u16ObjId" dx1="1733.33"/>
			<Connection Source="u16ObjIdA" Destination="RedGreenBackground4.u16ObjIdA" dx1="1733.33"/>
			<Connection Source="u16ObjIdB" Destination="RedGreenBackground4.u16ObjIdB" dx1="1886.67"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
