<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="RedWhiteBackground4_AXS" Comment="Hintergrundfarbe (TRUE -&gt; Rot, FALSE -&gt; Weiß) für 4 Objekte (AX-Adapter)">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="Franz Höpfinger" Date="2022-11-10">
	</VersionInfo>
	<CompilerInfo packageName="MyLib::sys">
		<Import declaration="isobus::UT::Q::const::IDs::ID_NULL"/>
		<Import declaration="isobus::UT::Q::const::colours::COLOR_WHITE"/>
		<Import declaration="isobus::UT::Q::const::colours::COLOR_RED"/>
		<Import declaration="isobus::UT::Q::types::s3ObjectIDs"/>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventOutputs>
			<SubAppEvent Name="CNF_1" Type="Event">
			</SubAppEvent>
			<SubAppEvent Name="CNF_2" Type="Event">
			</SubAppEvent>
			<SubAppEvent Name="CNF_3" Type="Event">
			</SubAppEvent>
			<SubAppEvent Name="CNF_4" Type="Event">
			</SubAppEvent>
		</SubAppEventOutputs>
		<InputVars>
			<VarDeclaration Name="u16ObjIds" Type="isobus::UT::Q::types::s3ObjectIDs" Comment="Object IDs" InitialValue="(u16ObjId := ID_NULL, u16ObjIdA := ID_NULL, u16ObjIdB := ID_NULL)"/>
		</InputVars>
		<OutputVars>
			<VarDeclaration Name="STATUS_1" Type="STRING" Comment="Service Status"/>
			<VarDeclaration Name="u8OldColour_1" Type="USINT" Comment="Old value of ID"/>
			<VarDeclaration Name="result_1" Type="INT" Comment="retval see description"/>
			<VarDeclaration Name="STATUS_2" Type="STRING" Comment="Service Status"/>
			<VarDeclaration Name="u8OldColour_2" Type="USINT" Comment="Old value of ID"/>
			<VarDeclaration Name="result_2" Type="INT" Comment="retval see description"/>
			<VarDeclaration Name="STATUS_3" Type="STRING" Comment="Service Status"/>
			<VarDeclaration Name="u8OldColour_3" Type="USINT" Comment="Old value of ID"/>
			<VarDeclaration Name="result_3" Type="INT" Comment="retval see description"/>
			<VarDeclaration Name="STATUS_4" Type="STRING" Comment="Service Status"/>
			<VarDeclaration Name="u8OldColour_4" Type="USINT" Comment="Old value of ID"/>
			<VarDeclaration Name="result_4" Type="INT" Comment="retval see description"/>
		</OutputVars>
		<Sockets>
			<AdapterDeclaration Name="DI1" Type="adapter::types::unidirectional::AX" Comment="Selector"/>
		</Sockets>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="Q_BackgroundColour_1" Type="isobus::UT::Q::Q_BackgroundColour" x="1000" y="500">
		</FB>
		<FB Name="Q_BackgroundColour_2" Type="isobus::UT::Q::Q_BackgroundColour" x="1000" y="1300">
		</FB>
		<FB Name="Q_BackgroundColour_3" Type="isobus::UT::Q::Q_BackgroundColourAux" x="1000" y="2100">
		</FB>
		<FB Name="Q_BackgroundColour_4" Type="isobus::UT::Q::Q_BackgroundColour" x="1000" y="2900">
		</FB>
		<FB Name="AX_SEL" Type="adapter::iec61131::selection::AX_SEL" x="-2100" y="3700">
			<Parameter Name="IN0" Value="COLOR_WHITE"/>
			<Parameter Name="IN1" Value="COLOR_RED"/>
		</FB>
		<FB Name="F_MOVE" Type="iec61131::selection::F_MOVE" x="-2500" y="1000">
			<Attribute Name="DataType" Value="isobus::UT::Q::types::s3ObjectIDs"/>
			<Parameter Name="OUT.u16ObjId" Value="">
				<Attribute Name="Visible" Value="true"/>
			</Parameter>
			<Parameter Name="OUT.u16ObjIdA" Value="">
				<Attribute Name="Visible" Value="true"/>
			</Parameter>
			<Parameter Name="OUT.u16ObjIdB" Value="">
				<Attribute Name="Visible" Value="true"/>
			</Parameter>
		</FB>
		<EventConnections>
			<Connection Source="Q_BackgroundColour_1.CNF" Destination="CNF_1" dx1="66.67"/>
			<Connection Source="Q_BackgroundColour_2.CNF" Destination="CNF_2" dx1="100"/>
			<Connection Source="Q_BackgroundColour_3.CNF" Destination="CNF_3" dx1="926.67"/>
			<Connection Source="Q_BackgroundColour_4.CNF" Destination="CNF_4" dx1="1100"/>
			<Connection Source="F_MOVE.CNF" Destination="Q_BackgroundColour_1.REQ" dx1="1273.33"/>
			<Connection Source="AX_SEL.CNF" Destination="F_MOVE.REQ" dx1="66.67" dx2="66.67" dy="-1120"/>
			<Connection Source="F_MOVE.CNF" Destination="Q_BackgroundColour_2.REQ" dx1="1326.67"/>
			<Connection Source="F_MOVE.CNF" Destination="Q_BackgroundColour_3.REQ" dx1="1326.67"/>
			<Connection Source="F_MOVE.CNF" Destination="Q_BackgroundColour_4.REQ" dx1="1326.67"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="F_MOVE.OUT.u16ObjId" Destination="Q_BackgroundColour_1.u16ObjId" dx1="1306.67"/>
			<Connection Source="Q_BackgroundColour_1.s16result" Destination="result_1" dx1="1200"/>
			<Connection Source="Q_BackgroundColour_1.u8OldColour" Destination="u8OldColour_1" dx1="1166.67"/>
			<Connection Source="Q_BackgroundColour_1.STATUS" Destination="STATUS_1" dx1="1133.33"/>
			<Connection Source="AX_SEL.OUT" Destination="Q_BackgroundColour_1.u8Colour" dx1="1213.33"/>
			<Connection Source="F_MOVE.OUT.u16ObjIdA" Destination="Q_BackgroundColour_2.u16ObjId" dx1="1406.67"/>
			<Connection Source="Q_BackgroundColour_2.s16result" Destination="result_2" dx1="1300"/>
			<Connection Source="Q_BackgroundColour_2.u8OldColour" Destination="u8OldColour_2" dx1="1266.67"/>
			<Connection Source="Q_BackgroundColour_2.STATUS" Destination="STATUS_2" dx1="1233.33"/>
			<Connection Source="AX_SEL.OUT" Destination="Q_BackgroundColour_2.u8Colour" dx1="1213.33"/>
			<Connection Source="F_MOVE.OUT.u16ObjIdA" Destination="Q_BackgroundColour_3.u16ObjId" dx1="1406.67"/>
			<Connection Source="Q_BackgroundColour_3.s16result" Destination="result_3" dx1="1260"/>
			<Connection Source="Q_BackgroundColour_3.u8OldColour" Destination="u8OldColour_3" dx1="1226.67"/>
			<Connection Source="Q_BackgroundColour_3.STATUS" Destination="STATUS_3" dx1="1193.33"/>
			<Connection Source="AX_SEL.OUT" Destination="Q_BackgroundColour_3.u8Colour" dx1="1213.33"/>
			<Connection Source="F_MOVE.OUT.u16ObjIdB" Destination="Q_BackgroundColour_4.u16ObjId" dx1="1373.33"/>
			<Connection Source="Q_BackgroundColour_4.s16result" Destination="result_4" dx1="1500"/>
			<Connection Source="Q_BackgroundColour_4.u8OldColour" Destination="u8OldColour_4" dx1="1466.67"/>
			<Connection Source="Q_BackgroundColour_4.STATUS" Destination="STATUS_4" dx1="1433.33"/>
			<Connection Source="AX_SEL.OUT" Destination="Q_BackgroundColour_4.u8Colour" dx1="1213.33"/>
			<Connection Source="u16ObjIds" Destination="F_MOVE.IN" dx1="1186.67"/>
		</DataConnections>
		<AdapterConnections>
			<Connection Source="DI1" Destination="AX_SEL.G" dx1="1153.33"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
