<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Maehwerksklappung" Comment="Mähwerksklappung Aufgabe Febr. 2026">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="Herr Lehrer" Date="2026-02-23">
	</VersionInfo>
	<CompilerInfo packageName="Meins">
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I2"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I3"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I4"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I5"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I6"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI_Events::BUTTON_PRESS_DOWN"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI_Events::BUTTON_PRESS_UP"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI_Events::BUTTON_SINGLE_CLICK"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q2"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q3"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q4"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q5"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q6"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="Ausgang_heben" Type="logiBUS::io::DQ::logiBUS_QXA" x="6700" y="2400">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="Output" Value="Output_Q1"/>
			<Parameter Name="QO" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="Ausgang_senken" Type="logiBUS::io::DQ::logiBUS_QXA" x="6700" y="600">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="Output" Value="Output_Q2"/>
			<Parameter Name="QO" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="Ausgang_entriegeln" Type="logiBUS::io::DQ::logiBUS_QXA" x="6700" y="-300">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="Output" Value="Output_Q4"/>
			<Parameter Name="QO" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="Ausgang_verriegeln" Type="logiBUS::io::DQ::logiBUS_QXA" x="6700" y="1500">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="Output" Value="Output_Q3"/>
			<Parameter Name="QO" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="Lampe_gruen" Type="logiBUS::io::DQ::logiBUS_QXA" x="7100" y="3400">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="Output" Value="Output_Q5"/>
			<Parameter Name="QO" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="Blinker_orange" Type="logiBUS::io::DQ::logiBUS_QXA" x="5700" y="4400">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="Output" Value="Output_Q6"/>
			<Parameter Name="QO" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="Arbeit" Type="logiBUS::io::DI::logiBUS_IE" x="800" y="-900">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="Input" Value="Input_I1"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
			<Parameter Name="QO" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="S_1B1_riegel_offen" Type="logiBUS::io::DI::logiBUS_IE" x="800" y="100">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="Input" Value="Input_I2"/>
			<Parameter Name="InputEvent" Value="BUTTON_PRESS_DOWN"/>
			<Parameter Name="QO" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="S_1B2_riegel_geschlossen" Type="logiBUS::io::DI::logiBUS_IE" x="600" y="2100">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="Input" Value="Input_I3"/>
			<Parameter Name="InputEvent" Value="BUTTON_PRESS_DOWN"/>
			<Parameter Name="QO" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="S_2B2_M_oben" Type="logiBUS::io::DI::logiBUS_IE" x="700" y="4000">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="Input" Value="Input_I5"/>
			<Parameter Name="InputEvent" Value="BUTTON_PRESS_DOWN"/>
			<Parameter Name="QO" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="S_2B1_M_unten" Type="logiBUS::io::DI::logiBUS_IE" x="700" y="1100">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="Input" Value="Input_I4"/>
			<Parameter Name="InputEvent" Value="BUTTON_PRESS_DOWN"/>
			<Parameter Name="QO" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="Transport" Type="logiBUS::io::DI::logiBUS_IE" x="700" y="3000">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="Input" Value="Input_I6"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
			<Parameter Name="QO" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="sequence_E_08_AX" Type="logiBUS::utils::sequence::event::sequence_E_08_AX" x="3200" y="-100">
		</FB>
		<Comment Comment="UNTEN" x="3400" y="500" width="1" height="1"/>
		<Comment Comment="S4 ist der Zustand &quot;Arbeit&quot;" x="-4300" y="3100" width="1500" height="306.67"/>
		<FB Name="AX_OR_entriegeln" Type="adapter::booleanOperators::AX_OR_2" x="5600" y="0">
		</FB>
		<FB Name="AX_OR_verriegeln" Type="adapter::booleanOperators::AX_OR_2" x="5400" y="1800">
		</FB>
		<Comment Comment="S8 ist Zustand &#10;&quot;Transport&quot;&#10;" x="-1300" y="1100" width="800" height="300"/>
		<FB Name="AX_OR_Lampe_gruen" Type="adapter::booleanOperators::AX_OR_2" x="4800" y="3700">
		</FB>
		<FB Name="S_1B2_riegel_geschlossen_1" Type="logiBUS::io::DI::logiBUS_IE" x="1900" y="4700">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="Input" Value="Input_I3"/>
			<Parameter Name="InputEvent" Value="BUTTON_PRESS_UP"/>
			<Parameter Name="QO" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="AX_BLINK" Type="adapter::events::unidirectional::signals::AX_BLINK" x="4200" y="4400">
			<Parameter Name="TIMELOW" Value="T#1s"/>
			<Parameter Name="TIMEHIGH" Value="T#500ms"/>
		</FB>
		<EventConnections>
			<Connection Source="Arbeit.IND" Destination="sequence_E_08_AX.START_S1" dx1="333.33"/>
			<Connection Source="S_1B1_riegel_offen.IND" Destination="sequence_E_08_AX.S1_S2" dx1="753.33"/>
			<Connection Source="S_2B1_M_unten.IND" Destination="sequence_E_08_AX.S2_S3" dx1="500"/>
			<Connection Source="S_1B2_riegel_geschlossen.IND" Destination="sequence_E_08_AX.S3_S4" dx1="806.67"/>
			<Connection Source="Transport.IND" Destination="sequence_E_08_AX.S4_S5" dx1="1100"/>
			<Connection Source="S_1B1_riegel_offen.IND" Destination="sequence_E_08_AX.S5_S6" dx1="753.33"/>
			<Connection Source="S_2B2_M_oben.IND" Destination="sequence_E_08_AX.S6_S7" dx1="1240"/>
			<Connection Source="S_1B2_riegel_geschlossen.IND" Destination="sequence_E_08_AX.S7_S8" dx1="1326.67"/>
			<Connection Source="Arbeit.IND" Destination="sequence_E_08_AX.S8_START" dx1="186.67"/>
			<Connection Source="S_1B2_riegel_geschlossen.IND" Destination="AX_BLINK.STOP" dx1="1480"/>
			<Connection Source="S_1B2_riegel_geschlossen_1.IND" Destination="AX_BLINK.START" dx1="613.33"/>
		</EventConnections>
		<AdapterConnections>
			<Connection Source="sequence_E_08_AX.DO_S1" Destination="AX_OR_entriegeln.IN1" dx1="633.33"/>
			<Connection Source="sequence_E_08_AX.DO_S2" Destination="Ausgang_senken.OUT" dx1="1673.33"/>
			<Connection Source="sequence_E_08_AX.DO_S3" Destination="AX_OR_verriegeln.IN1" dx1="1046.67"/>
			<Connection Source="AX_OR_entriegeln.OUT" Destination="Ausgang_entriegeln.OUT" dx1="253.33"/>
			<Connection Source="sequence_E_08_AX.DO_S5" Destination="AX_OR_entriegeln.IN2" dx1="733.33"/>
			<Connection Source="sequence_E_08_AX.DO_S6" Destination="Ausgang_heben.OUT" dx1="913.33"/>
			<Connection Source="AX_OR_verriegeln.OUT" Destination="Ausgang_verriegeln.OUT" dx1="253.33"/>
			<Connection Source="sequence_E_08_AX.DO_S7" Destination="AX_OR_verriegeln.IN2" dx1="666.67"/>
			<Connection Source="AX_OR_Lampe_gruen.OUT" Destination="Lampe_gruen.OUT" dx1="293.33"/>
			<Connection Source="sequence_E_08_AX.DO_S4" Destination="AX_OR_Lampe_gruen.IN1" dx1="300"/>
			<Connection Source="sequence_E_08_AX.DO_S8" Destination="AX_OR_Lampe_gruen.IN2" dx1="186.67"/>
			<Connection Source="AX_BLINK.OUT" Destination="Blinker_orange.OUT" dx1="400"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
