<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="ZylinderAusEinAutomatik" Comment="Motor Links/Rechtslauf">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23" Remarks="initial API and implementation and/or initial documentation">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I2"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I3"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI_Events::BUTTON_PRESS_DOWN"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI_Events::BUTTON_SINGLE_CLICK"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q5"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q56"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q6"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI_Events"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="Zylinder_aus" Type="logiBUS::io::DQ::logiBUS_QXA" x="-1400" y="-800">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q5"/>
		</FB>
		<FB Name="Zylinder_ein" Type="logiBUS::io::DQ::logiBUS_QXA" x="-1400" y="1400">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q6"/>
		</FB>
		<FB Name="AX_OR_2" Type="adapter::booleanOperators::AX_OR_2" x="-2700" y="800">
		</FB>
		<FB Name="Gnd" Type="logiBUS::io::DQ::logiBUS_QXA" x="-1400" y="300">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q56"/>
		</FB>
		<FB Name="AX_SPLIT_2_A" Type="adapter::events::unidirectional::AX_SPLIT_2" x="-4000" y="-300">
		</FB>
		<FB Name="AX_SPLIT_2_B" Type="adapter::events::unidirectional::AX_SPLIT_2" x="-4000" y="1900">
		</FB>
		<FB Name="DigitalInput_CLK_I1" Type="logiBUS::io::DI::logiBUS_IE" x="-7400" y="-900">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<FB Name="DigitalInput_CLK_I2" Type="logiBUS::io::DI::logiBUS_IE" x="-7400" y="200">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I2"/>
			<Parameter Name="InputEvent" Value="BUTTON_PRESS_DOWN"/>
		</FB>
		<FB Name="DigitalInput_CLK_I3" Type="logiBUS::io::DI::logiBUS_IE" x="-7400" y="1300">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I3"/>
			<Parameter Name="InputEvent" Value="BUTTON_PRESS_DOWN"/>
		</FB>
		<FB Name="AX_SR_1" Type="adapter::events::unidirectional::AX_SR" x="-5300" y="-500">
		</FB>
		<FB Name="AX_SR_2" Type="adapter::events::unidirectional::AX_SR" x="-5200" y="1700">
		</FB>
		<FB Name="E_DELAY" Type="iec61499::events::E_DELAY" x="-5800" y="700">
			<Parameter Name="DT" Value="T#50ms"/>
		</FB>
		<Comment Comment="Der Zylinder macht beim Ausfahren ein summendes Geräusch. &#10;" x="-500" y="-600" width="1500" height="533.33"/>
		<EventConnections>
			<Connection Source="DigitalInput_CLK_I1.IND" Destination="AX_SR_1.S" dx1="586.67"/>
			<Connection Source="DigitalInput_CLK_I2.IND" Destination="E_DELAY.START" dx1="606.67"/>
			<Connection Source="DigitalInput_CLK_I3.IND" Destination="AX_SR_2.R" dx1="393.33"/>
			<Connection Source="DigitalInput_CLK_I2.IND" Destination="AX_SR_1.R" dx1="586.67"/>
			<Connection Source="E_DELAY.EO" Destination="AX_SR_2.S" dx1="80" dx2="80" dy="500"/>
		</EventConnections>
		<AdapterConnections>
			<Connection Source="AX_SPLIT_2_A.OUT1" Destination="Zylinder_aus.OUT" dx1="920"/>
			<Connection Source="AX_SPLIT_2_B.OUT2" Destination="Zylinder_ein.OUT" dx1="920"/>
			<Connection Source="AX_OR_2.OUT" Destination="Gnd.OUT" dx1="340"/>
			<Connection Source="AX_SPLIT_2_A.OUT2" Destination="AX_OR_2.IN1" dx1="273.33"/>
			<Connection Source="AX_SPLIT_2_B.OUT1" Destination="AX_OR_2.IN2" dx1="273.33"/>
			<Connection Source="AX_SR_1.Q" Destination="AX_SPLIT_2_A.IN" dx1="386.67"/>
			<Connection Source="AX_SR_2.Q" Destination="AX_SPLIT_2_B.IN" dx1="333.33"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
