<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="mapping_Uebung_039" Comment="Spiegelabfolge V2 mit Schrittkette">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
				<Attribute Name="YPOSITION" Value="0"/>
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="Hutschienenmoped_XL_8_DO" Type="Hutschienenmoped_XL_8_DO" Comment="" x="-8800.0" y="-800.0">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
			<Parameter Name="u8SAMember" Value="GLOBAL" Comment=""/>
			<Parameter Name="u16ObjId" Value="ID_NULL" Comment=""/>
			<Parameter Name="DigitalOutput_Q1" Value="'Ventilsteuerung.functions.Q1.QX'" Comment=""/>
			<Parameter Name="DigitalOutput_Q2" Value="'Ventilsteuerung.functions.Q2.QX'" Comment=""/>
			<Parameter Name="DigitalOutput_Q3" Value="'Ventilsteuerung.functions.Q3.QX'" Comment=""/>
			<Parameter Name="DigitalOutput_Q4" Value="'Ventilsteuerung.functions.Q4.QX'" Comment=""/>
			<Parameter Name="DigitalOutput_Q8" Value="''" Comment=""/>
		</FB>
		<FB Name="UT_SoftkeyMapping_UP" Type="UT_SoftkeyMapping_UP" Comment="" x="-8800.0" y="1600.0">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
			<Parameter Name="u8SAMember" Value="GLOBAL" Comment=""/>
			<Parameter Name="u16ObjId_1" Value="SoftKey_F1" Comment=""/>
			<Parameter Name="DigitalInput_1" Value="'Ventilsteuerung.functions.SoftKey_F1_UP'" Comment=""/>
			<Parameter Name="u16ObjId_2" Value="SoftKey_F2" Comment=""/>
			<Parameter Name="DigitalInput_2" Value="'Ventilsteuerung.functions.SoftKey_F2_UP'" Comment=""/>
		</FB>
		<FB Name="Hutschienenmoped_XL_8_DI_DOWN" Type="Hutschienenmoped_XL_8_DI_DOWN" Comment="" x="-12800.0" y="-800.0">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
			<Parameter Name="u8SAMember" Value="GLOBAL" Comment=""/>
			<Parameter Name="u16ObjId" Value="ID_NULL" Comment=""/>
			<Parameter Name="DigitalInput_I1" Value="'Ventilsteuerung.functions.DigitalInput_DOWN_I1'" Comment=""/>
			<Parameter Name="DigitalInput_I2" Value="'Ventilsteuerung.functions.DigitalInput_DOWN_I2'" Comment=""/>
			<Parameter Name="DigitalInput_I3" Value="'Ventilsteuerung.functions.DigitalInput_DOWN_I3'" Comment=""/>
			<Parameter Name="DigitalInput_I4" Value="'Ventilsteuerung.functions.DigitalInput_DOWN_I4'" Comment=""/>
		</FB>
		<FB Name="UT_SoftkeyMapping" Type="UT_SoftkeyMapping" Comment="" x="-12800.0" y="1600.0">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
			<Parameter Name="u8SAMember" Value="GLOBAL" Comment=""/>
			<Parameter Name="u16ObjId_1" Value="SoftKey_F8" Comment=""/>
			<Parameter Name="DigitalInput_1" Value="'Ventilsteuerung.functions.Q1.IX'" Comment=""/>
			<Parameter Name="u16ObjId_2" Value="SoftKey_F2" Comment=""/>
			<Parameter Name="DigitalInput_2" Value="'Ventilsteuerung.functions.Q2.IX'" Comment=""/>
			<Parameter Name="DigitalInput_3" Value="''" Comment=""/>
			<Parameter Name="u16ObjId_4" Value="SoftKey_F9" Comment=""/>
			<Parameter Name="DigitalInput_4" Value="'Ventilsteuerung.functions.Q3.IX'" Comment=""/>
			<Parameter Name="u16ObjId_5" Value="SoftKey_F3" Comment=""/>
			<Parameter Name="DigitalInput_5" Value="'Ventilsteuerung.functions.Q4.IX'" Comment=""/>
		</FB>
		<EventConnections>
			<Connection Source="INIT" Destination="Hutschienenmoped_XL_8_DO.INIT" Comment="" dx1="73.33333333333334">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="UT_SoftkeyMapping_UP.INIT" Comment="" dx1="1733.3333333333335">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="Hutschienenmoped_XL_8_DI_DOWN.INIT" Comment="" dx1="400.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="UT_SoftkeyMapping.INIT" Comment="" dx1="1066.6666666666667">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
		</EventConnections>
	</SubAppNetwork>
</SubAppType>
