<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Ventilsteuerung" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="COLD" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<SubApp Name="mapping" Type="mapping" Comment="" x="133.33333333333334" y="-1066.6666666666667">
		</SubApp>
		<SubApp Name="functions" Type="Uebung_018" Comment="" x="133.33333333333334" y="-533.3333333333334">
		</SubApp>
		<EventConnections>
			<Connection Source="COLD" Destination="mapping.COLD" Comment="" dx1="733.3333333333334">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="COLD" Destination="functions.COLD" Comment="" dx1="800.0" dx2="800.0" dy="0.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
		</EventConnections>
	</SubAppNetwork>
</SubAppType>
