<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Speed_Selection" Comment="Waehlt aus den verfuegbaren Geschwindigkeitssignalen (VDS, WBSD, GBSD, MSS, NMEA) das vom Bediener ausgewaehlte Signal aus (je Quelle ausgelagert in eine eigene Auswahl-Subapp) und stellt Geschwindigkeit, Richtung und zurueckgelegte Distanz bereit">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="Elias" Date="2025-04-01">
	</VersionInfo>
	<CompilerInfo packageName="FBs::Baumsetzer::func::Automatik">
		<Import declaration="isobus::UT::Q::const::colours::COLOR_GREEN"/>
		<Import declaration="isobus::UT::Q::const::colours::COLOR_RED"/>
		<Import declaration="test::FBs::Baumsetzer::Constants::DefaultPool"/>
		<Import declaration="test::FBs::Baumsetzer::Constants::DefaultPool::Button_GBSD"/>
		<Import declaration="test::FBs::Baumsetzer::Constants::DefaultPool::Button_MSS"/>
		<Import declaration="test::FBs::Baumsetzer::Constants::DefaultPool::Button_NMEA"/>
		<Import declaration="test::FBs::Baumsetzer::Constants::DefaultPool::Button_VDS"/>
		<Import declaration="test::FBs::Baumsetzer::Constants::DefaultPool::Button_WBSD"/>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventOutputs>
			<SubAppEvent Name="CNF" Type="Event" Comment="Execution Confirmation">
			</SubAppEvent>
		</SubAppEventOutputs>
		<OutputVars>
			<VarDeclaration Name="Speed" Type="UDINT" Comment="Speed of selected Signal"/>
			<VarDeclaration Name="Direction" Type="UDINT" Comment="Direction of selected Signal"/>
			<VarDeclaration Name="Distance" Type="UDINT" Comment="Distance of selected Signal"/>
		</OutputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<SubApp Name="VDS_Auswahl" Type="FBs::Baumsetzer::func::Automatik::VDS_Auswahl" x="1500" y="200">
		</SubApp>
		<SubApp Name="WBSD_Auswahl" Type="FBs::Baumsetzer::func::Automatik::WBSD_Auswahl" x="1700" y="1400">
		</SubApp>
		<SubApp Name="GBSD_Auswahl" Type="FBs::Baumsetzer::func::Automatik::GBSD_Auswahl" x="1700" y="3200">
		</SubApp>
		<SubApp Name="MSS_Auswahl" Type="FBs::Baumsetzer::func::Automatik::MSS_Auswahl" x="1700" y="5000">
		</SubApp>
		<SubApp Name="NMEA_Auswahl" Type="FBs::Baumsetzer::func::Automatik::NMEA_Auswahl" x="1700" y="6700">
		</SubApp>
		<FB Name="F_UINT_TO_REAL" Type="iec61131::conversion::F_UINT_TO_REAL" x="4600" y="200">
		</FB>
		<FB Name="CYCLE_TIME" Type="logiBUS::utils::timing::CYCLE_TIME" x="4800" y="700">
		</FB>
		<FB Name="INTEGRAL" Type="logiBUS::utils::math::INTEGRAL" x="6100" y="200">
		</FB>
		<FB Name="F_SEL_E_Distance" Type="eclipse4diac::utils::selection::F_SEL_E_4" x="9700" y="1000">
		</FB>
		<FB Name="F_SEL_E_Speed" Type="eclipse4diac::utils::selection::F_SEL_E_4" x="9800" y="2400">
		</FB>
		<FB Name="F_SEL_E_Direction" Type="eclipse4diac::utils::selection::F_SEL_E_4" x="9800" y="4000">
		</FB>
		<FB Name="INTEGRAL_1" Type="logiBUS::utils::math::INTEGRAL" x="8100" y="6900">
		</FB>
		<FB Name="CYCLE_TIME_1" Type="logiBUS::utils::timing::CYCLE_TIME" x="4900" y="7400">
		</FB>
		<FB Name="F_UINT_TO_REAL_1" Type="iec61131::conversion::F_UINT_TO_REAL" x="6700" y="6900">
		</FB>
		<FB Name="F_SEL_E_Distance_2" Type="eclipse4diac::utils::selection::F_SEL_E_2" x="12800" y="1000">
		</FB>
		<FB Name="F_SEL_E_Speed_2" Type="eclipse4diac::utils::selection::F_SEL_E_2" x="12900" y="2400">
		</FB>
		<FB Name="F_SEL_E_Direction_2" Type="eclipse4diac::utils::selection::F_SEL_E_2" x="12800" y="4000">
		</FB>
		<FB Name="UDINT2UDINT" Type="iec61131::selection::F_MOVE" x="11000" y="1000">
			<Attribute Name="DataType" Value="UDINT"/>
		</FB>
		<FB Name="UDINT2UDINT_1" Type="iec61131::selection::F_MOVE" x="11000" y="2400">
			<Attribute Name="DataType" Value="UDINT"/>
		</FB>
		<FB Name="UDINT2UDINT_2" Type="iec61131::selection::F_MOVE" x="11000" y="4000">
			<Attribute Name="DataType" Value="UDINT"/>
		</FB>
		<FB Name="E_PERMIT" Type="iec61499::events::E_PERMIT" x="7300" y="200">
		</FB>
		<FB Name="E_PERMIT_1" Type="iec61499::events::E_PERMIT" x="4300" y="1700">
		</FB>
		<FB Name="E_PERMIT_2" Type="iec61499::events::E_PERMIT" x="4300" y="3500">
		</FB>
		<FB Name="E_PERMIT_4" Type="iec61499::events::E_PERMIT" x="9900" y="6900">
		</FB>
		<FB Name="F_SEL" Type="iec61131::selection::F_SEL" x="18600" y="500">
			<Parameter Name="IN0" Value="COLOR_RED"/>
			<Parameter Name="IN1" Value="COLOR_GREEN"/>
		</FB>
		<FB Name="Q_BackgroundColour" Type="isobus::UT::Q::Q_BackgroundColour" x="20900" y="400">
			<Parameter Name="u16ObjId" Value="Button_VDS"/>
		</FB>
		<FB Name="Q_BackgroundColour_1" Type="isobus::UT::Q::Q_BackgroundColour" x="20900" y="2300">
			<Parameter Name="u16ObjId" Value="Button_WBSD"/>
		</FB>
		<FB Name="F_SEL_1" Type="iec61131::selection::F_SEL" x="18600" y="2400">
			<Parameter Name="IN0" Value="COLOR_RED"/>
			<Parameter Name="IN1" Value="COLOR_GREEN"/>
		</FB>
		<FB Name="Q_BackgroundColour_2" Type="isobus::UT::Q::Q_BackgroundColour" x="20800" y="3800">
			<Parameter Name="u16ObjId" Value="Button_GBSD"/>
		</FB>
		<FB Name="F_SEL_2" Type="iec61131::selection::F_SEL" x="18600" y="3900">
			<Parameter Name="IN0" Value="COLOR_RED"/>
			<Parameter Name="IN1" Value="COLOR_GREEN"/>
		</FB>
		<FB Name="Q_BackgroundColour_3" Type="isobus::UT::Q::Q_BackgroundColour" x="20900" y="5200">
			<Parameter Name="u16ObjId" Value="Button_MSS"/>
		</FB>
		<FB Name="F_SEL_3" Type="iec61131::selection::F_SEL" x="18600" y="5300">
			<Parameter Name="IN0" Value="COLOR_RED"/>
			<Parameter Name="IN1" Value="COLOR_GREEN"/>
		</FB>
		<FB Name="Q_BackgroundColour_4" Type="isobus::UT::Q::Q_BackgroundColour" x="20900" y="6900">
			<Parameter Name="u16ObjId" Value="Button_NMEA"/>
		</FB>
		<FB Name="F_SEL_4" Type="iec61131::selection::F_SEL" x="18600" y="7000">
			<Parameter Name="IN0" Value="COLOR_RED"/>
			<Parameter Name="IN1" Value="COLOR_GREEN"/>
		</FB>
		<FB Name="Geschwindigkeit" Type="isobus::UT::Q::Q_NumericValue" x="4200" y="-4900">
			<Parameter Name="u16ObjId" Value="DefaultPool::OutputNumber_12000"/>
		</FB>
		<FB Name="Geschwindigkeit_1" Type="isobus::UT::Q::Q_NumericValue" x="4200" y="-4100">
			<Parameter Name="u16ObjId" Value="DefaultPool::OutputNumber_12004"/>
		</FB>
		<FB Name="Geschwindigkeit_2" Type="isobus::UT::Q::Q_NumericValue" x="4200" y="-3300">
			<Parameter Name="u16ObjId" Value="DefaultPool::OutputNumber_12005"/>
		</FB>
		<FB Name="Geschwindigkeit_3" Type="isobus::UT::Q::Q_NumericValue" x="4200" y="-2500">
			<Parameter Name="u16ObjId" Value="DefaultPool::OutputNumber_12006"/>
		</FB>
		<FB Name="Geschwindigkeit_4" Type="isobus::UT::Q::Q_NumericValue" x="4200" y="-1700">
			<Parameter Name="u16ObjId" Value="DefaultPool::OutputNumber_12007"/>
		</FB>
		<FB Name="F_MUL" Type="iec61131::arithmetic::F_MUL" x="4000" y="6900">
			<Parameter Name="IN2" Value="uint#10"/>
		</FB>
		<FB Name="CYCLE_TIME_2" Type="logiBUS::utils::timing::CYCLE_TIME" x="5100" y="5700">
		</FB>
		<FB Name="E_PERMIT_5" Type="iec61499::events::E_PERMIT" x="9800" y="5200">
		</FB>
		<FB Name="INTEGRAL_2" Type="logiBUS::utils::math::INTEGRAL" x="6600" y="5200">
		</FB>
		<FB Name="F_UINT_TO_REAL_2" Type="iec61131::conversion::F_UINT_TO_REAL" x="5100" y="5200">
		</FB>
		<FB Name="F_REAL_TO_UDINT" Type="iec61131::conversion::F_REAL_TO_UDINT" x="7300" y="800">
		</FB>
		<FB Name="F_REAL_TO_UDINT_1" Type="iec61131::conversion::F_REAL_TO_UDINT" x="8200" y="6000">
		</FB>
		<FB Name="F_REAL_TO_UDINT_2" Type="iec61131::conversion::F_REAL_TO_UDINT" x="9300" y="7600">
		</FB>
		<FB Name="UDINT2UDINT_Distance" Type="iec61131::selection::F_MOVE" x="24200" y="-4500">
			<Attribute Name="DataType" Value="UDINT"/>
		</FB>
		<FB Name="UDINT2UDINT_Speed" Type="iec61131::selection::F_MOVE" x="24300" y="-3900">
			<Attribute Name="DataType" Value="UDINT"/>
		</FB>
		<FB Name="UDINT2UDINT_Direction" Type="iec61131::selection::F_MOVE" x="24200" y="-3200">
			<Attribute Name="DataType" Value="UDINT"/>
		</FB>
		<FB Name="F_MOVE_5" Type="iec61131::selection::F_MOVE" x="4800" y="6900">
			<Attribute Name="DataType" Value="UINT"/>
		</FB>
		<EventConnections>
			<Connection Source="VDS_Auswahl.IND" Destination="F_UINT_TO_REAL.REQ" dx1="200"/>
			<Connection Source="VDS_Auswahl.IND" Destination="CYCLE_TIME.REQ" dx1="320"/>
			<Connection Source="F_UINT_TO_REAL.CNF" Destination="INTEGRAL.REQ" dx1="273.33"/>
			<Connection Source="F_UINT_TO_REAL_1.CNF" Destination="INTEGRAL_1.REQ" dx1="226.67"/>
			<Connection Source="F_SEL_E_Distance.CNF" Destination="UDINT2UDINT.REQ" dx1="286.67"/>
			<Connection Source="UDINT2UDINT.CNF" Destination="F_SEL_E_Distance_2.REQ1" dx1="593.33"/>
			<Connection Source="F_SEL_E_Speed.CNF" Destination="UDINT2UDINT_1.REQ" dx1="246.67"/>
			<Connection Source="UDINT2UDINT_1.CNF" Destination="F_SEL_E_Speed_2.REQ1" dx1="606.67"/>
			<Connection Source="F_SEL_E_Direction.CNF" Destination="UDINT2UDINT_2.REQ" dx1="220"/>
			<Connection Source="UDINT2UDINT_2.CNF" Destination="F_SEL_E_Direction_2.REQ1" dx1="606.67"/>
			<Connection Source="E_PERMIT.EO" Destination="F_SEL_E_Distance.REQ1" dx1="173.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INTEGRAL.CNF" Destination="E_PERMIT.EI" dx1="326.67"/>
			<Connection Source="E_PERMIT.EO" Destination="F_SEL_E_Speed.REQ1" dx1="406.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="E_PERMIT.EO" Destination="F_SEL_E_Direction.REQ1" dx1="440">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="WBSD_Auswahl.IND" Destination="E_PERMIT_1.EI" dx1="400"/>
			<Connection Source="E_PERMIT_1.EO" Destination="F_SEL_E_Distance.REQ2" dx1="1573.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="E_PERMIT_1.EO" Destination="F_SEL_E_Direction.REQ2" dx1="1640">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="E_PERMIT_1.EO" Destination="F_SEL_E_Speed.REQ2" dx1="1606.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="GBSD_Auswahl.IND" Destination="E_PERMIT_2.EI" dx1="400"/>
			<Connection Source="E_PERMIT_2.EO" Destination="F_SEL_E_Distance.REQ3" dx1="1520">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="E_PERMIT_2.EO" Destination="F_SEL_E_Speed.REQ3" dx1="1560">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="E_PERMIT_2.EO" Destination="F_SEL_E_Direction.REQ3" dx1="1586.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INTEGRAL_1.CNF" Destination="E_PERMIT_4.EI" dx1="626.67"/>
			<Connection Source="E_PERMIT_4.EO" Destination="F_SEL_E_Direction_2.REQ2" dx1="1160">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="E_PERMIT_4.EO" Destination="F_SEL_E_Distance_2.REQ2" dx1="1146.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="E_PERMIT_4.EO" Destination="F_SEL_E_Speed_2.REQ2" dx1="1160">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="F_SEL.CNF" Destination="Q_BackgroundColour.REQ" dx1="886.67"/>
			<Connection Source="F_SEL_1.CNF" Destination="Q_BackgroundColour_1.REQ" dx1="886.67"/>
			<Connection Source="F_SEL_2.CNF" Destination="Q_BackgroundColour_2.REQ" dx1="840"/>
			<Connection Source="F_SEL_3.CNF" Destination="Q_BackgroundColour_3.REQ" dx1="886.67"/>
			<Connection Source="F_SEL_4.CNF" Destination="Q_BackgroundColour_4.REQ" dx1="886.67"/>
			<Connection Source="VDS_Auswahl.Updated" Destination="F_SEL.REQ" dx1="8406.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="WBSD_Auswahl.Updated" Destination="F_SEL_1.REQ" dx1="8513.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="GBSD_Auswahl.Updated" Destination="F_SEL_2.REQ" dx1="6386.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="MSS_Auswahl.Updated" Destination="F_SEL_3.REQ" dx1="6386.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="NMEA_Auswahl.Updated" Destination="F_SEL_4.REQ" dx1="6286.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="WBSD_Auswahl.IND" Destination="Geschwindigkeit.REQ" dx1="320">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="VDS_Auswahl.IND" Destination="Geschwindigkeit_1.REQ" dx1="320">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="GBSD_Auswahl.IND" Destination="Geschwindigkeit_2.REQ" dx1="320">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="MSS_Auswahl.IND" Destination="Geschwindigkeit_3.REQ" dx1="320">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="NMEA_Auswahl.IND" Destination="F_MUL.REQ" dx1="180"/>
			<Connection Source="F_MOVE_5.CNF" Destination="CYCLE_TIME_1.REQ" dx1="80" dx2="80" dy="253.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="F_MOVE_5.CNF" Destination="F_UINT_TO_REAL_1.REQ">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="F_MOVE_5.CNF" Destination="Geschwindigkeit_4.REQ" dx1="80" dx2="80" dy="-4246.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="F_UINT_TO_REAL_2.CNF" Destination="INTEGRAL_2.REQ" dx1="280"/>
			<Connection Source="INTEGRAL_2.CNF" Destination="E_PERMIT_5.EI" dx1="1326.67"/>
			<Connection Source="MSS_Auswahl.IND" Destination="F_UINT_TO_REAL_2.REQ" dx1="766.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="MSS_Auswahl.IND" Destination="CYCLE_TIME_2.REQ" dx1="866.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="E_PERMIT_5.EO" Destination="F_SEL_E_Direction.REQ4" dx1="80" dx2="80" dy="-446.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="E_PERMIT_5.EO" Destination="F_SEL_E_Speed.REQ4" dx1="80" dx2="80" dy="-1246.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="E_PERMIT_5.EO" Destination="F_SEL_E_Distance.REQ4" dx1="80" dx2="80" dy="-1946.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="E_PERMIT.EO" Destination="F_REAL_TO_UDINT.REQ" dx1="80" dx2="80" dy="300">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="E_PERMIT_5.EO" Destination="F_REAL_TO_UDINT_1.REQ" dx1="80" dx2="80" dy="400"/>
			<Connection Source="E_PERMIT_4.EO" Destination="F_REAL_TO_UDINT_2.REQ" dx1="80" dx2="80" dy="346.67"/>
			<Connection Source="F_SEL_E_Distance_2.CNF" Destination="UDINT2UDINT_Distance.REQ" dx1="5346.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="UDINT2UDINT_Speed.CNF" Destination="CNF" dx1="2453.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="F_SEL_E_Speed_2.CNF" Destination="UDINT2UDINT_Speed.REQ" dx1="5333.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="F_SEL_E_Direction_2.CNF" Destination="UDINT2UDINT_Direction.REQ" dx1="5386.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="F_MUL.CNF" Destination="F_MOVE_5.REQ"/>
			<Connection Source="WBSD_Auswahl.Chosen" Destination="VDS_Auswahl.Reset" dx1="80" dx2="80" dy="-600">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="GBSD_Auswahl.Chosen" Destination="VDS_Auswahl.Reset" dx1="80" dx2="80" dy="-1500">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="MSS_Auswahl.Chosen" Destination="VDS_Auswahl.Reset" dx1="80" dx2="80" dy="-2146.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="NMEA_Auswahl.Chosen" Destination="VDS_Auswahl.Reset" dx1="80" dx2="80" dy="-3446.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="VDS_Auswahl.Chosen" Destination="WBSD_Auswahl.Reset" dx1="80" dx2="80" dy="746.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="GBSD_Auswahl.Chosen" Destination="WBSD_Auswahl.Reset" dx1="80" dx2="80" dy="-900">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="MSS_Auswahl.Chosen" Destination="WBSD_Auswahl.Reset" dx1="80" dx2="80" dy="-1546.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="NMEA_Auswahl.Chosen" Destination="WBSD_Auswahl.Reset" dx1="80" dx2="80" dy="-2846.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="VDS_Auswahl.Chosen" Destination="GBSD_Auswahl.Reset" dx1="80" dx2="80" dy="1646.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="WBSD_Auswahl.Chosen" Destination="GBSD_Auswahl.Reset" dx1="80" dx2="80" dy="900">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="MSS_Auswahl.Chosen" Destination="GBSD_Auswahl.Reset" dx1="80" dx2="80" dy="-646.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="NMEA_Auswahl.Chosen" Destination="GBSD_Auswahl.Reset" dx1="80" dx2="80" dy="-1946.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="VDS_Auswahl.Chosen" Destination="MSS_Auswahl.Reset" dx1="80" dx2="80" dy="2346.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="WBSD_Auswahl.Chosen" Destination="MSS_Auswahl.Reset" dx1="80" dx2="80" dy="1600">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="GBSD_Auswahl.Chosen" Destination="MSS_Auswahl.Reset" dx1="80" dx2="80" dy="700">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="NMEA_Auswahl.Chosen" Destination="MSS_Auswahl.Reset" dx1="80" dx2="80" dy="-1046.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="VDS_Auswahl.Chosen" Destination="NMEA_Auswahl.Reset" dx1="80" dx2="80" dy="3346.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="WBSD_Auswahl.Chosen" Destination="NMEA_Auswahl.Reset" dx1="80" dx2="80" dy="2600">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="GBSD_Auswahl.Chosen" Destination="NMEA_Auswahl.Reset" dx1="80" dx2="80" dy="1700">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="MSS_Auswahl.Chosen" Destination="NMEA_Auswahl.Reset" dx1="80" dx2="80" dy="1000">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
		</EventConnections>
		<DataConnections>
			<Connection Source="VDS_Auswahl.NavigationBasedVehicleSpeed" Destination="F_UINT_TO_REAL.IN" dx1="220"/>
			<Connection Source="VDS_Auswahl.timestamp_data" Destination="CYCLE_TIME.TM" dx1="353.33"/>
			<Connection Source="F_UINT_TO_REAL.OUT" Destination="INTEGRAL.IN" dx1="266.67"/>
			<Connection Source="CYCLE_TIME.CYCLE" Destination="INTEGRAL.TM" dx1="266.67"/>
			<Connection Source="WBSD_Auswahl.WHEELBASEDMACHINEDISTANCE" Destination="F_SEL_E_Distance.IN2" dx1="2026.67"/>
			<Connection Source="GBSD_Auswahl.GROUNDBASEDMACHINEDISTANCE" Destination="F_SEL_E_Distance.IN3" dx1="2106.67"/>
			<Connection Source="VDS_Auswahl.NavigationBasedVehicleSpeed" Destination="F_SEL_E_Speed.IN1" dx1="2266.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="WBSD_Auswahl.WHEELBASEDMACHINESPEED" Destination="F_SEL_E_Speed.IN2" dx1="2266.67"/>
			<Connection Source="GBSD_Auswahl.GROUNDBASEDMACHINESPEED" Destination="F_SEL_E_Speed.IN3" dx1="2266.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="MSS_Auswahl.SELECTEDMACHINESPEED" Destination="F_SEL_E_Speed.IN4" dx1="2266.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="MSS_Auswahl.SELECTEDMACHINEDIRECTION" Destination="F_SEL_E_Direction.IN4" dx1="2346.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="GBSD_Auswahl.GROUNDBASEDMACHINEDIRECTION" Destination="F_SEL_E_Direction.IN3" dx1="2346.67"/>
			<Connection Source="WBSD_Auswahl.WHEELBASEDMACHINEDIRECTION" Destination="F_SEL_E_Direction.IN2" dx1="2346.67"/>
			<Connection Source="WBSD_Auswahl.WHEELBASEDMACHINEDIRECTION" Destination="F_SEL_E_Direction.IN1" dx1="2346.67"/>
			<Connection Source="WBSD_Auswahl.WHEELBASEDMACHINEDIRECTION" Destination="F_SEL_E_Direction_2.IN2" dx1="2093.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="CYCLE_TIME_1.CYCLE" Destination="INTEGRAL_1.TM" dx1="266.67"/>
			<Connection Source="F_UINT_TO_REAL_1.OUT" Destination="INTEGRAL_1.IN" dx1="226.67"/>
			<Connection Source="NMEA_Auswahl.timestamp_data" Destination="CYCLE_TIME_1.TM" dx1="626.67"/>
			<Connection Source="F_SEL_E_Distance.OUT" Destination="UDINT2UDINT.IN" dx1="220"/>
			<Connection Source="F_SEL_E_Speed.OUT" Destination="UDINT2UDINT_1.IN" dx1="186.67"/>
			<Connection Source="UDINT2UDINT_1.OUT" Destination="F_SEL_E_Speed_2.IN1" dx1="540"/>
			<Connection Source="NMEA_Auswahl.SpeedOverGround" Destination="F_SEL_E_Speed_2.IN2" dx1="6820">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="F_SEL_E_Direction.OUT" Destination="UDINT2UDINT_2.IN" dx1="340"/>
			<Connection Source="UDINT2UDINT_2.OUT" Destination="F_SEL_E_Direction_2.IN1" dx1="533.33"/>
			<Connection Source="GBSD_Auswahl.Selected" Destination="E_PERMIT_2.PERMIT" dx1="1166.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="NMEA_Auswahl.Selected" Destination="E_PERMIT_4.PERMIT" dx1="3086.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="F_SEL.OUT" Destination="Q_BackgroundColour.u8Colour" dx1="346.67"/>
			<Connection Source="F_SEL_1.OUT" Destination="Q_BackgroundColour_1.u8Colour" dx1="880"/>
			<Connection Source="GBSD_Auswahl.Selected" Destination="F_SEL_2.G" dx1="6386.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="F_SEL_2.OUT" Destination="Q_BackgroundColour_2.u8Colour" dx1="833.33"/>
			<Connection Source="F_SEL_3.OUT" Destination="Q_BackgroundColour_3.u8Colour" dx1="880"/>
			<Connection Source="MSS_Auswahl.Selected" Destination="F_SEL_3.G" dx1="6386.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="F_SEL_4.OUT" Destination="Q_BackgroundColour_4.u8Colour" dx1="880"/>
			<Connection Source="NMEA_Auswahl.Selected" Destination="F_SEL_4.G" dx1="8246.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="WBSD_Auswahl.WHEELBASEDMACHINESPEED" Destination="Geschwindigkeit.u32NewValue" dx1="320">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="VDS_Auswahl.NavigationBasedVehicleSpeed" Destination="Geschwindigkeit_1.u32NewValue" dx1="320">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="GBSD_Auswahl.GROUNDBASEDMACHINESPEED" Destination="Geschwindigkeit_2.u32NewValue" dx1="320">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="MSS_Auswahl.SELECTEDMACHINESPEED" Destination="Geschwindigkeit_3.u32NewValue" dx1="320">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="NMEA_Auswahl.SpeedOverGround" Destination="F_MUL.IN1" dx1="120"/>
			<Connection Source="F_MOVE_5.OUT" Destination="F_UINT_TO_REAL_1.IN"/>
			<Connection Source="F_MOVE_5.OUT" Destination="Geschwindigkeit_4.u32NewValue" dx1="80" dx2="80" dy="-4200">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="CYCLE_TIME_2.CYCLE" Destination="INTEGRAL_2.TM" dx1="266.67"/>
			<Connection Source="F_UINT_TO_REAL_2.OUT" Destination="INTEGRAL_2.IN" dx1="266.67"/>
			<Connection Source="MSS_Auswahl.timestamp_data" Destination="CYCLE_TIME_2.TM" dx1="866.67"/>
			<Connection Source="MSS_Auswahl.SELECTEDMACHINESPEED" Destination="F_UINT_TO_REAL_2.IN" dx1="766.67"/>
			<Connection Source="MSS_Auswahl.Selected" Destination="E_PERMIT_5.PERMIT" dx1="2940">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INTEGRAL.OUT" Destination="F_REAL_TO_UDINT.IN" dx1="260"/>
			<Connection Source="INTEGRAL_2.OUT" Destination="F_REAL_TO_UDINT_1.IN" dx1="460"/>
			<Connection Source="F_REAL_TO_UDINT_1.OUT" Destination="F_SEL_E_Distance.IN4" dx1="246.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INTEGRAL_1.OUT" Destination="F_REAL_TO_UDINT_2.IN" dx1="253.33"/>
			<Connection Source="F_REAL_TO_UDINT_2.OUT" Destination="F_SEL_E_Distance_2.IN2" dx1="1826.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="F_SEL_E_Distance_2.OUT" Destination="UDINT2UDINT_Distance.IN" dx1="5346.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="UDINT2UDINT_Speed.OUT" Destination="Speed" dx1="2453.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="UDINT2UDINT_Direction.OUT" Destination="Direction" dx1="1093.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="UDINT2UDINT_Distance.OUT" Destination="Distance" dx1="1013.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="F_SEL_E_Speed_2.OUT" Destination="UDINT2UDINT_Speed.IN" dx1="5333.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="F_SEL_E_Direction_2.OUT" Destination="UDINT2UDINT_Direction.IN" dx1="5386.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="F_REAL_TO_UDINT.OUT" Destination="F_SEL_E_Distance.IN1" dx1="1013.33"/>
			<Connection Source="UDINT2UDINT.OUT" Destination="F_SEL_E_Distance_2.IN1" dx1="1220"/>
			<Connection Source="VDS_Auswahl.Selected" Destination="E_PERMIT.PERMIT" dx1="2460">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="VDS_Auswahl.Selected" Destination="F_SEL.G" dx1="8406.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="WBSD_Auswahl.Selected" Destination="E_PERMIT_1.PERMIT" dx1="1213.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="WBSD_Auswahl.Selected" Destination="F_SEL_1.G" dx1="8513.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="F_MUL.OUT" Destination="F_MOVE_5.IN"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
