<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_004" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="COLD" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="QX" Comment="" x="-1466.6666666666667" y="-933.3333333333334">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalInput_I1_CLK" Type="IE" Comment="" x="-4533.333333333334" y="-933.3333333333334">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="E_T_FF" Type="E_T_FF" Comment="" x="-2800.0" y="-633.3333333333334">
		</FB>
		<EventConnections>
			<Connection Source="COLD" Destination="DigitalInput_I1_CLK.INIT" Comment="" dx1="1113.3333333333335">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="DigitalInput_I1_CLK.INITO" Destination="DigitalOutput_Q1.INIT" Comment=""/>
			<Connection Source="DigitalInput_I1_CLK.IND" Destination="E_T_FF.CLK" Comment="" dx1="473.33333333333337"/>
			<Connection Source="E_T_FF.EO" Destination="DigitalOutput_Q1.REQ" Comment="" dx1="400.0"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_T_FF.Q" Destination="DigitalOutput_Q1.OUT" Comment=""/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
