<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_005" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="COLD" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="QX" Comment="" x="-1200.0" y="-466.6666666666667">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="E_T_FF" Type="E_T_FF" Comment="" x="-2533.3333333333335" y="-166.66666666666669">
		</FB>
		<FB Name="DigitalInput_I1" Type="IX" Comment="" x="-5733.333333333334" y="-566.6666666666667">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="E_SWITCH" Type="E_SWITCH" Comment="" x="-4000.0" y="-266.6666666666667">
		</FB>
		<EventConnections>
			<Connection Source="E_T_FF.EO" Destination="DigitalOutput_Q1.REQ" Comment="" dx1="400.0"/>
			<Connection Source="COLD" Destination="DigitalInput_I1.INIT" Comment="" dx1="340.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="DigitalInput_I1.INITO" Destination="DigitalOutput_Q1.INIT" Comment="" dx1="1933.3333333333335"/>
			<Connection Source="DigitalInput_I1.IND" Destination="E_SWITCH.EI" Comment="" dx1="520.0"/>
			<Connection Source="E_SWITCH.EO1" Destination="E_T_FF.CLK" Comment=""/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_T_FF.Q" Destination="DigitalOutput_Q1.OUT" Comment=""/>
			<Connection Source="DigitalInput_I1.IN" Destination="E_SWITCH.G" Comment=""/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
