<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_039" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
				<Attribute Name="YPOSITION" Value="46"/>
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<SubApp Name="Q1" Type="Uebung_039_sub_Outputs" Comment="" x="400.0" y="-1066.6666666666667">
			<Parameter Name="u16ObjId" Value="SoftKey_F8" Comment=""/>
		</SubApp>
		<SubApp Name="Q2" Type="Uebung_039_sub_Outputs" Comment="" x="400.0" y="-266.6666666666667">
			<Parameter Name="u16ObjId" Value="SoftKey_F2" Comment=""/>
		</SubApp>
		<SubApp Name="Q3" Type="Uebung_039_sub_Outputs" Comment="" x="400.0" y="533.3333333333334">
			<Parameter Name="u16ObjId" Value="SoftKey_F9" Comment=""/>
		</SubApp>
		<SubApp Name="Q4" Type="Uebung_039_sub_Outputs" Comment="" x="400.0" y="1333.3333333333335">
			<Parameter Name="u16ObjId" Value="SoftKey_F3" Comment=""/>
		</SubApp>
		<FB Name="sequence_ET_05" Type="sequence_ET_05" Comment="" x="-2266.666666666667" y="-533.3333333333334">
			<Parameter Name="DT_S1_S2" Value="NO_TIME" Comment=""/>
			<Parameter Name="DT_S2_S3" Value="NO_TIME" Comment=""/>
			<Parameter Name="DT_S3_S4" Value="T#5s" Comment=""/>
			<Parameter Name="DT_S4_S5" Value="NO_TIME" Comment=""/>
			<Parameter Name="DT_S5_START" Value="NO_TIME" Comment=""/>
		</FB>
		<FB Name="E_TimeOut" Type="E_TimeOut" Comment="" x="400.0" y="2266.666666666667">
		</FB>
		<FB Name="SoftKey_F1_UP" Type="IE" Comment="" x="-3466.666666666667" y="-3866.666666666667">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalInput_DOWN_I1" Type="IE" Comment="" x="-4666.666666666667" y="-3066.666666666667">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalInput_DOWN_I2" Type="IE" Comment="" x="-4666.666666666667" y="-2133.3333333333335">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalInput_DOWN_I3" Type="IE" Comment="" x="-4666.666666666667" y="-1200.0">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalInput_DOWN_I4" Type="IE" Comment="" x="-4666.666666666667" y="-266.6666666666667">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<EventConnections>
			<Connection Source="INIT" Destination="Q1.INIT" Comment="" dx1="1193.3333333333335">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="Q2.INIT" Comment="" dx1="1193.3333333333335">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="Q3.INIT" Comment="" dx1="1193.3333333333335">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="Q4.INIT" Comment="" dx1="1193.3333333333335">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="sequence_ET_05.EO_S1" Destination="Q1.REQ" Comment="" dx1="573.3333333333334"/>
			<Connection Source="sequence_ET_05.EO_S2" Destination="Q2.REQ" Comment="" dx1="626.6666666666667"/>
			<Connection Source="sequence_ET_05.EO_S4" Destination="Q3.REQ" Comment="" dx1="626.6666666666667"/>
			<Connection Source="sequence_ET_05.EO_S5" Destination="Q4.REQ" Comment="" dx1="593.3333333333334"/>
			<Connection Source="INIT" Destination="SoftKey_F1_UP.INIT" Comment="" dx1="986.6666666666667">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalInput_DOWN_I1.INIT" Comment="" dx1="993.3333333333334">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalInput_DOWN_I2.INIT" Comment="" dx1="993.3333333333334">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalInput_DOWN_I3.INIT" Comment="" dx1="926.6666666666667">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalInput_DOWN_I4.INIT" Comment="" dx1="860.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="SoftKey_F1_UP.IND" Destination="sequence_ET_05.START_S1" Comment="" dx1="253.33333333333334"/>
			<Connection Source="DigitalInput_DOWN_I1.IND" Destination="sequence_ET_05.S1_S2" Comment="" dx1="1026.6666666666667"/>
			<Connection Source="DigitalInput_DOWN_I2.IND" Destination="sequence_ET_05.S2_S3" Comment="" dx1="886.6666666666667"/>
			<Connection Source="DigitalInput_DOWN_I3.IND" Destination="sequence_ET_05.S4_S5" Comment="" dx1="793.3333333333334"/>
			<Connection Source="DigitalInput_DOWN_I4.IND" Destination="sequence_ET_05.S5_START" Comment="" dx1="793.3333333333334"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="sequence_ET_05.DO_S1" Destination="Q1.DI" Comment="" dx1="660.0"/>
			<Connection Source="sequence_ET_05.DO_S2" Destination="Q2.DI" Comment="" dx1="693.3333333333334"/>
			<Connection Source="sequence_ET_05.DO_S4" Destination="Q3.DI" Comment="" dx1="806.6666666666667"/>
			<Connection Source="sequence_ET_05.DO_S5" Destination="Q4.DI" Comment="" dx1="560.0"/>
		</DataConnections>
		<AdapterConnections>
			<Connection Source="sequence_ET_05.timeOut" Destination="E_TimeOut.TimeOutSocket" Comment="" dx1="526.6666666666667"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
