<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_018" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="COLD" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="SoftKey_F1_UP" Type="IE" Comment="" x="-4533.333333333334" y="-1066.6666666666667">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="Q_CtrlAudioSignal" Type="Q_CtrlAudioSignal" Comment="" x="-2400.0" y="-1066.6666666666667">
			<Parameter Name="u8NumOfRepit" Value="1" Comment=""/>
			<Parameter Name="u16Frequency" Value="440" Comment=""/>
			<Parameter Name="u16OnTimeMs" Value="150" Comment=""/>
			<Parameter Name="u16OffTimeMs" Value="0" Comment=""/>
		</FB>
		<FB Name="Q_CtrlAudioSignal_1" Type="Q_CtrlAudioSignal" Comment="" x="-1333.3333333333335" y="266.6666666666667">
			<Parameter Name="u8NumOfRepit" Value="1" Comment=""/>
			<Parameter Name="u16Frequency" Value="880" Comment=""/>
			<Parameter Name="u16OnTimeMs" Value="150" Comment=""/>
			<Parameter Name="u16OffTimeMs" Value="0" Comment=""/>
		</FB>
		<FB Name="E_DELAY" Type="E_DELAY" Comment="" x="-2533.3333333333335" y="533.3333333333334">
			<Parameter Name="DT" Value="T#250ms" Comment=""/>
		</FB>
		<EventConnections>
			<Connection Source="COLD" Destination="SoftKey_F1_UP.INIT" Comment="" dx1="1113.3333333333335">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="SoftKey_F1_UP.INITO" Destination="Q_CtrlAudioSignal.INIT" Comment=""/>
			<Connection Source="SoftKey_F1_UP.IND" Destination="Q_CtrlAudioSignal.REQ" Comment="" dx1="720.0"/>
			<Connection Source="SoftKey_F1_UP.INITO" Destination="Q_CtrlAudioSignal_1.INIT" Comment="" dx1="1080.0"/>
			<Connection Source="E_DELAY.EO" Destination="Q_CtrlAudioSignal_1.REQ" Comment="" dx1="293.33333333333337"/>
			<Connection Source="SoftKey_F1_UP.IND" Destination="E_DELAY.START" Comment="" dx1="653.3333333333334"/>
		</EventConnections>
	</SubAppNetwork>
</SubAppType>
