<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_007" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="COLD" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="QX" Comment="" x="-400.0" y="-866.6666666666667">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="E_CYCLE" Type="E_CYCLE" Comment="" x="-2933.3333333333335" y="-566.6666666666667">
			<Parameter Name="DT" Value="T#1s" Comment=""/>
		</FB>
		<FB Name="E_T_FF" Type="E_T_FF" Comment="" x="-1600.0" y="-566.6666666666667">
		</FB>
		<EventConnections>
			<Connection Source="E_CYCLE.EO" Destination="E_T_FF.CLK" Comment=""/>
			<Connection Source="E_T_FF.EO" Destination="DigitalOutput_Q1.REQ" Comment="" dx1="333.33333333333337"/>
			<Connection Source="COLD" Destination="DigitalOutput_Q1.INIT" Comment="" dx1="1813.3333333333335">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="COLD" Destination="E_CYCLE.START" Comment="" dx1="533.3333333333334">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_T_FF.Q" Destination="DigitalOutput_Q1.OUT" Comment=""/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
