<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_039_sub_Outputs" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2024-03-03">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="Service Initialization">
			</SubAppEvent>
			<SubAppEvent Name="REQ" Type="Event" Comment="Service Request">
			</SubAppEvent>
		</SubAppEventInputs>
		<InputVars>
			<VarDeclaration Name="DI" Type="BOOL" Comment="Digital Input"/>
			<VarDeclaration Name="u16ObjId" Type="UINT" Comment="Object ID Softkey/Button" InitialValue="ID_NULL"/>
		</InputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="QX" Type="QX" Comment="" x="3333.3333333333335" y="0.0">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="IX" Type="IX" Comment="" x="0.0" y="-113.33333333333334">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<SubApp Name="GreenWhiteBackground" Type="GreenWhiteBackground" Comment="" x="4933.333333333334" y="933.3333333333334">
		</SubApp>
		<FB Name="OR_2" Type="OR_2" Comment="" x="1466.6666666666667" y="226.66666666666669">
		</FB>
		<EventConnections>
			<Connection Source="IX.INITO" Destination="QX.INIT" Comment="" dx1="1920.0"/>
			<Connection Source="INIT" Destination="IX.INIT" Comment="" dx1="660.0"/>
			<Connection Source="QX.INITO" Destination="GreenWhiteBackground.INIT" Comment="" dx1="453.33333333333337"/>
			<Connection Source="QX.CNF" Destination="GreenWhiteBackground.REQ" Comment="" dx1="313.33333333333337"/>
			<Connection Source="OR_2.CNF" Destination="QX.REQ" Comment="" dx1="546.6666666666667"/>
			<Connection Source="IX.IND" Destination="OR_2.REQ" Comment="" dx1="393.33333333333337"/>
			<Connection Source="REQ" Destination="OR_2.REQ" Comment="" dx1="2640.0"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="u16ObjId" Destination="GreenWhiteBackground.u16ObjId" Comment="" dx1="526.6666666666667"/>
			<Connection Source="OR_2.OUT" Destination="GreenWhiteBackground.DI1" Comment="" dx1="360.0"/>
			<Connection Source="OR_2.OUT" Destination="QX.OUT" Comment="" dx1="546.6666666666667"/>
			<Connection Source="IX.IN" Destination="OR_2.IN2" Comment=""/>
			<Connection Source="DI" Destination="OR_2.IN1" Comment="" dx1="2253.3333333333335"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
