<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_016" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="COLD" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="SoftKey_F1_UP" Type="IE" Comment="" x="-4533.333333333334" y="-1066.6666666666667">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="SoftKey_F2_UP" Type="IE" Comment="" x="-4533.333333333334" y="266.6666666666667">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="E_SR" Type="E_SR" Comment="" x="-2800.0" y="-866.6666666666667">
		</FB>
		<FB Name="F_SEL" Type="F_SEL" Comment="" x="-1066.6666666666667" y="-800.0">
			<Parameter Name="IN0" Value="COLOR_WHITE" Comment=""/>
			<Parameter Name="IN1" Value="COLOR_GREEN" Comment=""/>
		</FB>
		<FB Name="Q_BackgroundColour" Type="Q_BackgroundColour" Comment="" x="800.0" y="-1200.0">
			<Parameter Name="u16ObjId" Value="SoftKey_F7" Comment=""/>
		</FB>
		<EventConnections>
			<Connection Source="COLD" Destination="SoftKey_F1_UP.INIT" Comment="" dx1="1113.3333333333335">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="COLD" Destination="SoftKey_F2_UP.INIT" Comment="" dx1="1206.6666666666667">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="SoftKey_F1_UP.IND" Destination="E_SR.S" Comment=""/>
			<Connection Source="SoftKey_F2_UP.IND" Destination="E_SR.R" Comment="" dx1="473.33333333333337"/>
			<Connection Source="E_SR.EO" Destination="F_SEL.REQ" Comment="" dx1="633.3333333333334"/>
			<Connection Source="COLD" Destination="Q_BackgroundColour.INIT" Comment="" dx1="3733.3333333333335" dx2="3733.3333333333335" dy="0.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="F_SEL.CNF" Destination="Q_BackgroundColour.REQ" Comment="" dx1="266.6666666666667" dx2="266.6666666666667" dy="0.0"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_SR.Q" Destination="F_SEL.G" Comment="" dx1="633.3333333333334"/>
			<Connection Source="F_SEL.OUT" Destination="Q_BackgroundColour.u8Colour" Comment="" dx1="673.3333333333334"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
