<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_014" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="COLD" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="SoftKey_F1_UP" Type="IE" Comment="" x="-4533.333333333334" y="-1066.6666666666667">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="SoftKey_F2_UP" Type="IE" Comment="" x="-4533.333333333334" y="266.6666666666667">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="E_SR" Type="E_SR" Comment="" x="-2800.0" y="-866.6666666666667">
		</FB>
		<FB Name="Q_ObjHideShow" Type="Q_ObjHideShow" Comment="" x="-1466.6666666666667" y="-1066.6666666666667">
			<Parameter Name="u16ObjId" Value="Container_B" Comment=""/>
		</FB>
		<EventConnections>
			<Connection Source="COLD" Destination="SoftKey_F1_UP.INIT" Comment="" dx1="1113.3333333333335">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="COLD" Destination="SoftKey_F2_UP.INIT" Comment="" dx1="1206.6666666666667">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="SoftKey_F1_UP.IND" Destination="E_SR.S" Comment=""/>
			<Connection Source="SoftKey_F2_UP.IND" Destination="E_SR.R" Comment="" dx1="473.33333333333337"/>
			<Connection Source="SoftKey_F1_UP.INITO" Destination="Q_ObjHideShow.INIT" Comment=""/>
			<Connection Source="E_SR.EO" Destination="Q_ObjHideShow.REQ" Comment="" dx1="433.33333333333337"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_SR.Q" Destination="Q_ObjHideShow.qVisible" Comment="" dx1="433.33333333333337"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
