<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_015" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="COLD" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="SoftKey_F1_UP" Type="IE" Comment="" x="-4533.333333333334" y="-1066.6666666666667">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="SoftKey_F2_UP" Type="IE" Comment="" x="-4533.333333333334" y="266.6666666666667">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="E_SR" Type="E_SR" Comment="" x="-2800.0" y="-866.6666666666667">
		</FB>
		<FB Name="F_UINT_TO_UDINT" Type="F_UINT_TO_UDINT" Comment="" x="-2800.0" y="0.0">
			<Parameter Name="IN" Value="Button_A1" Comment=""/>
		</FB>
		<FB Name="F_SEL" Type="F_SEL" Comment="" x="-1066.6666666666667" y="-800.0">
			<Parameter Name="IN0" Value="ID_NULL" Comment=""/>
		</FB>
		<FB Name="Q_NumericValue" Type="Q_NumericValue" Comment="" x="800.0" y="-1200.0">
			<Parameter Name="u16ObjId" Value="ObjectPointer_P1" Comment=""/>
		</FB>
		<EventConnections>
			<Connection Source="COLD" Destination="SoftKey_F1_UP.INIT" Comment="" dx1="1113.3333333333335">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="COLD" Destination="SoftKey_F2_UP.INIT" Comment="" dx1="1206.6666666666667">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="SoftKey_F1_UP.IND" Destination="E_SR.S" Comment=""/>
			<Connection Source="SoftKey_F2_UP.IND" Destination="E_SR.R" Comment="" dx1="473.33333333333337"/>
			<Connection Source="F_SEL.CNF" Destination="Q_NumericValue.REQ" Comment="" dx1="266.6666666666667"/>
			<Connection Source="E_SR.EO" Destination="F_SEL.REQ" Comment="" dx1="633.3333333333334"/>
			<Connection Source="COLD" Destination="Q_NumericValue.INIT" Comment="" dx1="3733.3333333333335">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="COLD" Destination="F_UINT_TO_UDINT.REQ" Comment="" dx1="1933.3333333333335">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
		</EventConnections>
		<DataConnections>
			<Connection Source="F_SEL.OUT" Destination="Q_NumericValue.u32NewValue" Comment="" dx1="673.3333333333334"/>
			<Connection Source="F_UINT_TO_UDINT.OUT" Destination="F_SEL.IN1" Comment="" dx1="373.33333333333337"/>
			<Connection Source="E_SR.Q" Destination="F_SEL.G" Comment="" dx1="633.3333333333334"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
