<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_001" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="COLD" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalInput_I1" Type="IX" Comment="" x="-4533.333333333334" y="-933.3333333333334">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<EventConnections>
			<Connection Source="COLD" Destination="DigitalInput_I1.INIT" Comment="" dx1="1073.3333333333335">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
		</EventConnections>
	</SubAppNetwork>
</SubAppType>
