<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_008" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="COLD" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="QX" Comment="" x="533.3333333333334" y="-866.6666666666667">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="E_CYCLE" Type="E_CYCLE" Comment="" x="-3733.3333333333335" y="-666.6666666666667">
			<Parameter Name="DT" Value="T#1s" Comment=""/>
		</FB>
		<FB Name="E_SWITCH" Type="E_SWITCH" Comment="" x="-2266.666666666667" y="-666.6666666666667">
		</FB>
		<FB Name="E_SR" Type="E_SR" Comment="" x="-666.6666666666667" y="-666.6666666666667">
		</FB>
		<EventConnections>
			<Connection Source="COLD" Destination="DigitalOutput_Q1.INIT" Comment="" dx1="1813.3333333333335">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="COLD" Destination="E_CYCLE.START" Comment="" dx1="193.33333333333334">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="E_CYCLE.EO" Destination="E_SWITCH.EI" Comment=""/>
			<Connection Source="E_SWITCH.EO0" Destination="E_SR.S" Comment=""/>
			<Connection Source="E_SWITCH.EO1" Destination="E_SR.R" Comment=""/>
			<Connection Source="E_SR.EO" Destination="DigitalOutput_Q1.REQ" Comment="" dx1="380.0"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_SR.Q" Destination="E_SWITCH.G" Comment="" dx1="80.0" dx2="80.0" dy="160.0"/>
			<Connection Source="E_SR.Q" Destination="DigitalOutput_Q1.OUT" Comment=""/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
