<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_010" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="COLD" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="QX" Comment="" x="-1466.6666666666667" y="-833.3333333333334">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="SoftKey_F1" Type="IX" Comment="" x="-4533.333333333334" y="-933.3333333333334">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<EventConnections>
			<Connection Source="COLD" Destination="SoftKey_F1.INIT" Comment="" dx1="1073.3333333333335">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="SoftKey_F1.INITO" Destination="DigitalOutput_Q1.INIT" Comment="" dx1="1200.0"/>
			<Connection Source="SoftKey_F1.IND" Destination="DigitalOutput_Q1.REQ" Comment=""/>
		</EventConnections>
		<DataConnections>
			<Connection Source="SoftKey_F1.IN" Destination="DigitalOutput_Q1.OUT" Comment=""/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
