<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_012" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="COLD" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="F_DWORD_TO_UDINT" Type="F_DWORD_TO_UDINT" Comment="" x="-2666.666666666667" y="1066.6666666666667">
		</FB>
		<FB Name="InputNumber_I1" Type="ID" Comment="" x="-3733.3333333333335" y="666.6666666666667">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="NVS_UDINT" Type="NVS_UDINT" Comment="" x="-933.3333333333334" y="666.6666666666667">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
			<Parameter Name="KEY" Value="KEY_I1_STORE" Comment=""/>
		</FB>
		<FB Name="Q_NumericValue" Type="Q_NumericValue" Comment="" x="800.0" y="800.0">
			<Parameter Name="u16ObjId" Value="InputNumber_I1" Comment=""/>
		</FB>
		<FB Name="CbVtStatus" Type="CbVtStatus" Comment="" x="-3733.3333333333335" y="-400.0">
		</FB>
		<EventConnections>
			<Connection Source="InputNumber_I1.IND" Destination="F_DWORD_TO_UDINT.REQ" Comment="" dx1="300.0"/>
			<Connection Source="COLD" Destination="InputNumber_I1.INIT" Comment="" dx1="833.3333333333334">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="COLD" Destination="NVS_UDINT.INIT" Comment="" dx1="2533.3333333333335">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="F_DWORD_TO_UDINT.CNF" Destination="NVS_UDINT.SET" Comment="" dx1="380.0"/>
			<Connection Source="NVS_UDINT.INITO" Destination="NVS_UDINT.GET" Comment="" dx1="80.0" dx2="480.0" dy="-253.33333333333334"/>
			<Connection Source="NVS_UDINT.GETO" Destination="Q_NumericValue.REQ" Comment="" dx1="513.3333333333334"/>
			<Connection Source="NVS_UDINT.INITO" Destination="Q_NumericValue.INIT" Comment="" dx1="513.3333333333334"/>
			<Connection Source="COLD" Destination="CbVtStatus.INIT" Comment="" dx1="1466.6666666666667">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="CbVtStatus.IND" Destination="Q_NumericValue.REQ" Comment="" dx1="3513.3333333333335"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="InputNumber_I1.IN" Destination="F_DWORD_TO_UDINT.IN" Comment=""/>
			<Connection Source="F_DWORD_TO_UDINT.OUT" Destination="NVS_UDINT.VALUE" Comment=""/>
			<Connection Source="NVS_UDINT.VALUEO" Destination="Q_NumericValue.u32NewValue" Comment="" dx1="313.33333333333337"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
