<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="AX_2_TO_3" Comment="Konvertierung von 2 auf 3 AX-Adapter Signale">
	<Identification Standard="61499-2" Description="Copyright (c) 2026 HR Agrartechnik GmbH  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="HR Agrartechnik GmbH  " Version="1.0" Author="Franz Höpfinger" Date="2026-04-19">
	</VersionInfo>
	<CompilerInfo packageName="MyLib::sys">
	</CompilerInfo>
	<SubAppInterfaceList>
		<Plugs>
			<AdapterDeclaration Name="UP_OUT" Type="adapter::types::unidirectional::AX"/>
			<AdapterDeclaration Name="OR_OUT" Type="adapter::types::unidirectional::AX"/>
			<AdapterDeclaration Name="DOWN_OUT" Type="adapter::types::unidirectional::AX"/>
		</Plugs>
		<Sockets>
			<AdapterDeclaration Name="UP_IN" Type="adapter::types::unidirectional::AX"/>
			<AdapterDeclaration Name="DOWN_IN" Type="adapter::types::unidirectional::AX"/>
		</Sockets>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="AX_SPLIT_DOWN" Type="adapter::events::unidirectional::AX_SPLIT_2" x="900" y="-200">
		</FB>
		<FB Name="AX_SPLIT_UP" Type="adapter::events::unidirectional::AX_SPLIT_2" x="900" y="-1100">
		</FB>
		<FB Name="AX_OR_2" Type="adapter::booleanOperators::AX_OR_2" x="2300" y="-700">
		</FB>
		<AdapterConnections>
			<Connection Source="AX_SPLIT_DOWN.OUT1" Destination="AX_OR_2.IN2" dx1="466.67"/>
			<Connection Source="AX_SPLIT_UP.OUT2" Destination="AX_OR_2.IN1" dx1="500"/>
			<Connection Source="DOWN_IN" Destination="AX_SPLIT_DOWN.IN" dx1="520"/>
			<Connection Source="AX_SPLIT_DOWN.OUT2" Destination="DOWN_OUT" dx1="2026.67"/>
			<Connection Source="UP_IN" Destination="AX_SPLIT_UP.IN" dx1="1346.67"/>
			<Connection Source="AX_SPLIT_UP.OUT1" Destination="UP_OUT" dx1="813.33"/>
			<Connection Source="AX_OR_2.OUT" Destination="OR_OUT" dx1="360"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
