<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="GreenWhiteBackground3_AX" Comment="Hintergrundfarbe (TRUE -&gt; Grün, FALSE -&gt; Weiß) für 3 Objekte (AX-Adapter)">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="Franz Höpfinger" Date="2022-11-10">
	</VersionInfo>
	<CompilerInfo packageName="MyLib::sys">
		<Import declaration="isobus::UT::Q::const::IDs::ID_NULL"/>
		<Import declaration="isobus::UT::Q::const::colours::COLOR_WHITE"/>
		<Import declaration="isobus::UT::Q::const::colours::COLOR_GREEN"/>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventOutputs>
			<SubAppEvent Name="CNF_1" Type="Event">
			</SubAppEvent>
			<SubAppEvent Name="CNF_2" Type="Event">
			</SubAppEvent>
			<SubAppEvent Name="CNF_3" Type="Event">
			</SubAppEvent>
		</SubAppEventOutputs>
		<InputVars>
			<VarDeclaration Name="u16ObjId" Type="UINT" Comment="Object ID Softkey" InitialValue="ID_NULL"/>
			<VarDeclaration Name="u16ObjIdA" Type="UINT" Comment="Object ID AUX" InitialValue="ID_NULL"/>
		</InputVars>
		<OutputVars>
			<VarDeclaration Name="STATUS_1" Type="STRING" Comment="Service Status"/>
			<VarDeclaration Name="u8OldColour_1" Type="USINT" Comment="Old value of ID"/>
			<VarDeclaration Name="result_1" Type="INT" Comment="retval see description"/>
			<VarDeclaration Name="STATUS_2" Type="STRING" Comment="Service Status"/>
			<VarDeclaration Name="u8OldColour_2" Type="USINT" Comment="Old value of ID"/>
			<VarDeclaration Name="result_2" Type="INT" Comment="retval see description"/>
			<VarDeclaration Name="STATUS_3" Type="STRING" Comment="Service Status"/>
			<VarDeclaration Name="u8OldColour_3" Type="USINT" Comment="Old value of ID"/>
			<VarDeclaration Name="result_3" Type="INT" Comment="retval see description"/>
		</OutputVars>
		<Sockets>
			<AdapterDeclaration Name="DI1" Type="adapter::types::unidirectional::AX" Comment="Selector"/>
		</Sockets>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="Q_BackgroundColour_1" Type="isobus::UT::Q::Q_BackgroundColour" x="1000" y="500">
		</FB>
		<FB Name="Q_BackgroundColour_2" Type="isobus::UT::Q::Q_BackgroundColour" x="1000" y="1300">
		</FB>
		<FB Name="Q_BackgroundColour_3" Type="isobus::UT::Q::Q_BackgroundColourAux" x="1000" y="2100">
		</FB>
		<FB Name="AX_SEL" Type="adapter::iec61131::selection::AX_SEL" x="-1000" y="1000">
			<Parameter Name="IN0" Value="COLOR_WHITE"/>
			<Parameter Name="IN1" Value="COLOR_GREEN"/>
		</FB>
		<EventConnections>
			<Connection Source="Q_BackgroundColour_1.CNF" Destination="CNF_1" dx1="1080"/>
			<Connection Source="Q_BackgroundColour_2.CNF" Destination="CNF_2" dx1="1113.33"/>
			<Connection Source="Q_BackgroundColour_3.CNF" Destination="CNF_3" dx1="1006.67"/>
			<Connection Source="AX_SEL.CNF" Destination="Q_BackgroundColour_1.REQ" dx1="733.33"/>
			<Connection Source="AX_SEL.CNF" Destination="Q_BackgroundColour_2.REQ" dx1="633.33"/>
			<Connection Source="AX_SEL.CNF" Destination="Q_BackgroundColour_3.REQ" dx1="633.33"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="u16ObjId" Destination="Q_BackgroundColour_1.u16ObjId" dx1="5200"/>
			<Connection Source="Q_BackgroundColour_1.s16result" Destination="result_1" dx1="1246.67"/>
			<Connection Source="Q_BackgroundColour_1.u8OldColour" Destination="u8OldColour_1" dx1="1213.33"/>
			<Connection Source="Q_BackgroundColour_1.STATUS" Destination="STATUS_1" dx1="1180"/>
			<Connection Source="AX_SEL.OUT" Destination="Q_BackgroundColour_1.u8Colour" dx1="766.67"/>
			<Connection Source="u16ObjIdA" Destination="Q_BackgroundColour_2.u16ObjId" dx1="5133.33"/>
			<Connection Source="Q_BackgroundColour_2.s16result" Destination="result_2" dx1="1346.67"/>
			<Connection Source="Q_BackgroundColour_2.u8OldColour" Destination="u8OldColour_2" dx1="1313.33"/>
			<Connection Source="Q_BackgroundColour_2.STATUS" Destination="STATUS_2" dx1="1280"/>
			<Connection Source="AX_SEL.OUT" Destination="Q_BackgroundColour_2.u8Colour" dx1="666.67"/>
			<Connection Source="u16ObjIdA" Destination="Q_BackgroundColour_3.u16ObjId" dx1="5133.33"/>
			<Connection Source="Q_BackgroundColour_3.s16result" Destination="result_3" dx1="1306.67"/>
			<Connection Source="Q_BackgroundColour_3.u8OldColour" Destination="u8OldColour_3" dx1="1273.33"/>
			<Connection Source="Q_BackgroundColour_3.STATUS" Destination="STATUS_3" dx1="1240"/>
			<Connection Source="AX_SEL.OUT" Destination="Q_BackgroundColour_3.u8Colour" dx1="666.67"/>
		</DataConnections>
		<AdapterConnections>
			<Connection Source="DI1" Destination="AX_SEL.G" dx1="1920"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
