<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="INI_IN_AND_STORE_AUDI" Comment="Initialisierung und Speicherung von AUDI-Daten">
	<Identification Standard="61499-2" Description="Copyright (c) 2026 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-04-24" Remarks="initial API and implementation (AX version)">
	</VersionInfo>
	<CompilerInfo packageName="MyLib::sys">
		<Import declaration="isobus::UT::Q::const::IDs::ID_NULL"/>
	</CompilerInfo>
	<SubAppInterfaceList>
		<InputVars>
			<VarDeclaration Name="KEY" Type="STRING"/>
			<VarDeclaration Name="SECTION" Type="STRING"/>
			<VarDeclaration Name="u16ObjId" Type="UINT" InitialValue="ID_NULL"/>
		</InputVars>
		<Plugs>
			<AdapterDeclaration Name="VALUEO" Type="adapter::types::unidirectional::AUDI"/>
		</Plugs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="INI_AUDI" Type="eclipse4diac::storage::INI_AUDI" x="800" y="-93.33">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="DEFAULT_VALUE" Value="UDINT#0"/>
		</FB>
		<FB Name="ID" Type="isobus::UT::io::NumericValue::NumericValue_IDA" x="-2800" y="-200">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="Q_NumericValue_AUDI" Type="isobus::UT::Q::Q_NumericValue_AUDI" x="5600" y="-93.33">
		</FB>
		<FB Name="AD_TO_AUDI" Type="adapter::conversion::unidirectional::AD_TO_AUDI" x="-900" y="333.33">
		</FB>
		<FB Name="AUDI_SPLIT_2" Type="adapter::events::unidirectional::AUDI_SPLIT_2" x="3100" y="226.67">
		</FB>
		<DataConnections>
			<Connection Source="u16ObjId" Destination="Q_NumericValue_AUDI.u16ObjId" dx1="8246.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="KEY" Destination="INI_AUDI.KEY" dx1="2846.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="SECTION" Destination="INI_AUDI.SECTION" dx1="2846.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="u16ObjId" Destination="ID.u16ObjId" dx1="1046.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
		</DataConnections>
		<AdapterConnections>
			<Connection Source="INI_AUDI.AUDI_OUT" Destination="AUDI_SPLIT_2.IN" dx1="106.67"/>
			<Connection Source="ID.IN" Destination="AD_TO_AUDI.AD_IN"/>
			<Connection Source="AD_TO_AUDI.AUDI_OUT" Destination="INI_AUDI.AUDI_IN"/>
			<Connection Source="AUDI_SPLIT_2.OUT1" Destination="VALUEO" dx1="2220">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="AUDI_SPLIT_2.OUT2" Destination="Q_NumericValue_AUDI.u32NewValue"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
