<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="INI_IN_AND_STORE_AR" Comment="Initialisierung und Speicherung von AR-Daten">
	<Identification Standard="61499-2" Description="Copyright (c) 2026 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-04-24" Remarks="AR adapter variant for PHYS REAL INI storage with Subapp">
	</VersionInfo>
	<CompilerInfo packageName="MyLib::sys">
		<Import declaration="isobus::UT::Q::const::IDs::ID_NULL"/>
		<Import declaration="logiBUS::utils::conversion::phys::NumericObjectPool_S"/>
	</CompilerInfo>
	<SubAppInterfaceList>
		<InputVars>
			<VarDeclaration Name="KEY" Type="STRING"/>
			<VarDeclaration Name="SECTION" Type="STRING"/>
			<VarDeclaration Name="stObj" Type="logiBUS::utils::conversion::phys::NumericObjectPool_S" InitialValue="(u16ObjId := ID_NULL, r32Scale := 1.0, i32Offset := 0, u8Decimals := 0)"/>
		</InputVars>
		<Plugs>
			<AdapterDeclaration Name="VALUEO" Type="adapter::types::unidirectional::AR"/>
		</Plugs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="INI_AR" Type="eclipse4diac::storage::INI_AR" x="800" y="-200">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="DEFAULT_VALUE" Value="REAL#0.0"/>
		</FB>
		<FB Name="NumericValue_PHYSA" Type="isobus::UT::io::NumericValue::NumericValue_PHYSA" x="-2800" y="-200">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="Q_NumericValue_PHYSA" Type="isobus::UT::Q::Q_NumericValue_PHYSA" x="5600" y="0">
		</FB>
		<FB Name="AR_SPLIT_2" Type="adapter::events::unidirectional::AR_SPLIT_2" x="3100" y="300">
		</FB>
		<DataConnections>
			<Connection Source="stObj" Destination="Q_NumericValue_PHYSA.stObj" dx1="8246.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="KEY" Destination="INI_AR.KEY" dx1="2846.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="SECTION" Destination="INI_AR.SECTION" dx1="2846.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="stObj" Destination="NumericValue_PHYSA.stObj" dx1="1046.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
		</DataConnections>
		<AdapterConnections>
			<Connection Source="INI_AR.AR_OUT" Destination="AR_SPLIT_2.IN" dx1="106.67"/>
			<Connection Source="NumericValue_PHYSA.rPhys" Destination="INI_AR.AR_IN"/>
			<Connection Source="AR_SPLIT_2.OUT1" Destination="VALUEO" dx1="2220">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="AR_SPLIT_2.OUT2" Destination="Q_NumericValue_PHYSA.rPhys" dx1="873.33"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
