<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="NVS_IN_AND_STORE_AIS" Comment="NVS Laden und Speichern von AIS-Daten">
	<Identification Standard="61499-2" Description="Copyright (c) 2026 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-04-24" Remarks="AIS adapter variant for String NVS storage with Subapp">
	</VersionInfo>
	<CompilerInfo packageName="MyLib::sys">
		<Import declaration="isobus::UT::Q::const::IDs::ID_NULL"/>
	</CompilerInfo>
	<SubAppInterfaceList>
		<InputVars>
			<VarDeclaration Name="KEY" Type="STRING"/>
			<VarDeclaration Name="u16ObjId" Type="UINT" InitialValue="ID_NULL"/>
		</InputVars>
		<Plugs>
			<AdapterDeclaration Name="VALUEO" Type="adapter::types::unidirectional::AIS"/>
		</Plugs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="NVS_AIS" Type="logiBUS::storage::esp32_nvs::NVS_AIS" x="800" y="-93.33">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="DEFAULT_VALUE" Value="STRING#''"/>
		</FB>
		<FB Name="StringValue_AIS" Type="isobus::UT::io::StringValue::StringValue_AIS" x="-2800" y="-200">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="Q_StringValue_AIS" Type="isobus::UT::Q::Q_StringValue_AIS" x="5600" y="-93.33">
		</FB>
		<FB Name="AIS_SPLIT_2" Type="adapter::events::unidirectional::AIS_SPLIT_2" x="3100" y="226.67">
		</FB>
		<DataConnections>
			<Connection Source="u16ObjId" Destination="Q_StringValue_AIS.u16ObjId" dx1="8246.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="KEY" Destination="NVS_AIS.KEY" dx1="2846.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="u16ObjId" Destination="StringValue_AIS.u16ObjId" dx1="1046.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
		</DataConnections>
		<AdapterConnections>
			<Connection Source="NVS_AIS.AIS_OUT" Destination="AIS_SPLIT_2.IN" dx1="106.67"/>
			<Connection Source="StringValue_AIS.IN" Destination="NVS_AIS.AIS_IN"/>
			<Connection Source="AIS_SPLIT_2.OUT1" Destination="VALUEO" dx1="2220">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="AIS_SPLIT_2.OUT2" Destination="Q_StringValue_AIS.pau8String"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
