<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="RedGreenBackground1" Comment="Hintergrundfarbe (TRUE -> Rot, FALSE -> Grün) für 1 Objekt">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2022-11-10">
	</VersionInfo>
	<CompilerInfo packageName="MyLib::sys">
		<Import declaration="isobus::UT::Q::const::IDs::ID_NULL"/>
		<Import declaration="isobus::UT::Q::const::colours"/>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="REQ" Type="Event" Comment="Normal Execution Request">
			</SubAppEvent>
		</SubAppEventInputs>
		<SubAppEventOutputs>
			<SubAppEvent Name="CNF_1" Type="Event" Comment="Execution Confirmation">
			</SubAppEvent>
		</SubAppEventOutputs>
		<InputVars>
			<VarDeclaration Name="DI1" Type="BOOL" Comment="Selector"/>
			<VarDeclaration Name="u16ObjId" Type="UINT" Comment="Object ID Softkey" InitialValue="ID_NULL"/>
		</InputVars>
		<OutputVars>
			<VarDeclaration Name="STATUS_1" Type="STRING" Comment="Service Status"/>
			<VarDeclaration Name="u8OldColour_1" Type="USINT" Comment="Old value of ID"/>
			<VarDeclaration Name="result_1" Type="INT" Comment="retval see description"/>
		</OutputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="Q_BackgroundColour" Type="isobus::UT::Q::Q_BackgroundColour" x="933.33" y="933.33">
		</FB>
		<FB Name="F_SEL_I" Type="iec61131::selection::F_SEL" x="-266.67" y="2266.67">
			<Parameter Name="IN0" Value="colours::COLOR_GREEN"/>
			<Parameter Name="IN1" Value="colours::COLOR_RED"/>
		</FB>
		<EventConnections>
			<Connection Source="Q_BackgroundColour.CNF" Destination="CNF_1" dx1="960"/>
			<Connection Source="F_SEL_I.CNF" Destination="Q_BackgroundColour.REQ" dx1="373.33"/>
			<Connection Source="REQ" Destination="F_SEL_I.REQ" dx1="473.33"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="u16ObjId" Destination="Q_BackgroundColour.u16ObjId" dx1="1126.67"/>
			<Connection Source="Q_BackgroundColour.s16result" Destination="result_1" dx1="926.67"/>
			<Connection Source="Q_BackgroundColour.u8OldColour" Destination="u8OldColour_1" dx1="960"/>
			<Connection Source="Q_BackgroundColour.STATUS" Destination="STATUS_1" dx1="946.67"/>
			<Connection Source="F_SEL_I.OUT" Destination="Q_BackgroundColour.u8Colour" dx1="406.67"/>
			<Connection Source="DI1" Destination="F_SEL_I.G" dx1="440"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
