<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="tastend_TON_5s" Comment="Tastende Funktion mit 5s Einschaltverzögerung (AX-Adapter)">
	<Identification Standard="61499-2" Description="Copyright (c) 2024 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2024-10-23">
	</VersionInfo>
	<CompilerInfo packageName="MyLib::sys">
	</CompilerInfo>
	<SubAppInterfaceList>
		<Plugs>
			<AdapterDeclaration Name="OUT" Type="adapter::types::unidirectional::AX"/>
		</Plugs>
		<Sockets>
			<AdapterDeclaration Name="IN" Type="adapter::types::unidirectional::AX"/>
		</Sockets>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="E_TON" Type="adapter::events::unidirectional::timers::AX_TON" x="-8300" y="-1900">
			<Parameter Name="PT" Value="t#5s"/>
		</FB>
		<AdapterConnections>
			<Connection Source="IN" Destination="E_TON.IN" dx1="1046.67"/>
			<Connection Source="E_TON.Q" Destination="OUT" dx1="7540"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
